#ifndef GENERATOR_H
#define GENERATOR_H

const int vtipyPocet = 100;
const char* vtipy[] = {
  "Přijde programátor domů a žena mu říká: Zajdi do obchodu a kup rohlíky. Když budou mít vejce, kup deset. Přinesl deset rohlíků.",
  "Jak se jmenuje nejrychlejší ryba? Šika, protože se říká šika to jde!",
  "Jaký je rozdíl mezi školou a blázincem? V blázinci se musíš vyléčit, aby tě pustili.",
  "Potká krokodýl jezevce. Jezevec: Ahoj krokodýle! Krokodýl: Ahoj jezevčíku! Jezevec: Já nejsem jezevčík! Krokodýl: To já zas nejsem krokodýlek!",
  "Volá Pepíček mamince: Mami, nebudu dneska ve škole obědvat! Proč? Protože je sobota, Pepíčku.",
  "Doktor říká pacientovi: Mám dvě zprávy. Pacient: Tak tu špatnou. Máte 24 hodin života. A ta velmi špatná? Volám vám od včerejška.",
  "Učitelka: Kolik je 5 krát 5? Pepíček: 25! A kolik je 5 krát 6? To je jiná pohádka, paní učitelko.",
  "Přijde muž k doktorovi: Pane doktore, všichni mě ignorují. Doktor: Další prosím!",
  "Jaký je rozdíl mezi politikem a létajícím talířem? Žádný, oba slibují a nikdy nepřistanou.",
  "Manželka: Miláčku, co bys dělal, kdybych vyhrála v loterii? Manžel: Vzal bych si polovinu a odešel. Manželka: Vyhrála jsem 200 Kč, tady máš stovku!",
  // 11-20
  "Pepíček ve škole: Paní učitelko, můžu být potrestaný za něco, co jsem neudělal? Ne, Pepíčku. Tak já jsem neudělal domácí úkol.",
  "Dva mrtvoly leží v márnici. Jedna říká: Na co jsi umřel? Na chřipku. A ty? Já ještě neumřel, ale je tu taková zima...",
  "Přijde muž do knihovny: Jednu pizzu prosím. Paní, tohle je knihovna! Muž šeptá: Promiňte, jednu pizzu prosím.",
  "Jaký je rozdíl mezi koněm a šachovou figurkou? Kůň nejí šikmo.",
  "Učitel: Kdo vymyslel elektřinu? Žák: Nikola Tesla. Učitel: Správně! Žák: Ale zaplatit ji vymyslel ČEZ.",
  "Víte proč programátoři nosí brýle? Protože nevidí C#.",
  "Manželka: Ty mě vůbec neposloucháš! Manžel: To je ale divný začátek konverzace.",
  "Co dělá kočka na počítači? Loví myš.",
  "Pepíček: Tati, jak se píše tma? Táta: Nevím. Pepíček: Ale jo, musíš to vědět, včera jsi řekl mamce, že seš v práci úplně ve tmě!",
  "Přijde opilec domů a říká ženě: Ty seš ale ošklivá! A ráno se probudí a říká: Ježiš, tak to nebyl sen!",
  // 21-30
  "Doktor: Musíte přestat pít! Pacient: Ale já nepiju. Doktor: Tak musíte začít, protože bez alkoholu ten můj účet nevydržíte.",
  "Dva kamarádi: Koupil jsem si slovník. A co jsi se dozvěděl? Že aardvark je zvíře.",
  "Volá policista na stanici: Tady je mrtvola s dvaceti bodnými ranami. Vypadá to na sebevraždu? Ne, vypadá to jako sebevražda, ale mohla by to být i alergie.",
  "Pepíček: Mami, ve škole mi říkají lhář! Máma: Pepíčku, ty přece nechodíš do školy!",
  "Co má společného programátor a kočka? Oba nenávidí myši a nemají rádi Okna.",
  "Přijde muž do restaurace: Máte žabí stehýnka? Číšník: Nemáme. Muž: Tak skáčete normálně?",
  "Jaký je nejlepší antivirus? Zdravý rozum. Bohužel většina lidí používá pirátskou verzi.",
  "Učitelka: Pepíčku, řekni mi větu s podmětem já. Pepíček: Já... Učitelka: A co dál? Pepíček: A to je celá věta, jsem přece egoist.",
  "Co říká jeden hrob druhému? Nekopej do mě!",
  "Manžel čte noviny: Drahá, píšou tu že ženy mluví dvakrát víc než muži. Manželka: To proto, že vám musíme všechno opakovat!",
  // 31-40
  "Přijde muž k doktorovi: Doktore, zlomil jsem si ruku na dvou místech. Doktor: Tak na ta místa nechoďte.",
  "Proč nemůžeš věřit atomům? Protože tvoří úplně všechno.",
  "Žena volá manželovi: Miláčku, auto mi nejede! Manžel: Jaký benzín jsi tam dala? Žena: Ten voňavý z koupelny.",
  "Jaký je rozdíl mezi tebou a kalendářem? Kalendář má rande každý den.",
  "Pepíček: Tati, je pravda, že v Africe člověk neví, co ho čeká? Táta: Pravda. Pepíček: Tak proto jsi si vzal maminku?",
  "Dva kamarádi v kině: Ten film byl úplně nereálný. Proč? Hlavní hrdina měl plnou baterii v telefonu celý den!",
  "Volá pacient doktorovi: Doktore, spolkl jsem lžičku! Doktor: Sedněte si a nemíchejte se!",
  "Co je na konci vesmíru? Písmeno U.",
  "Manželka: Dneska bych chtěla něco s diamantem. Manžel: Co takhle balíček karet?",
  "Přijde muž do obchodu: Máte neviditelný inkoust? Prodavač: Jistě, co by jste chtěl aby tam bylo napsáno?",
  // 41-50
  "Dva informatici v baru: Moje žena mě nechápe. Druhý: Zkus ji restartovat.",
  "Učitelka: Co je to gravitace? Pepíček: Je to síla, která způsobuje, že ráno padám z postele.",
  "Proč nosí potápěči padák? Pro případ, že by klesla hladina.",
  "Manžel: Koupil jsem ti nový vysavač! Manželka: Super! A kdo s ním bude vysávat? Manžel: Nikdo, funguje sám. Na baterie. Manželka: A kdo ho bude nabíjet?",
  "Přijde student na zkoušku. Profesor: Co víte o elektřině? Student: Že nemáme svítit na chodbě.",
  "Co řekne pes, když sedí na brusném papíru? Rrruff!",
  "Pepíček: Tati, koupíš mi encyklopedii? Táta: Ne, budeš chodit pěšky jako já.",
  "Proč jsou matematici špatní v zahradnictví? Protože pořád počítají se záporným kořenem.",
  "Doktor: Kolik hodin spíte? Pacient: Asi osm. Doktor: To je moc. Pacient: Tak se probudím po šesti. Doktor: Ale jen ve všední dny.",
  "Dva kamarádi: Víš že ryby jsou chytré? Proč? Protože jsou pořád ve škole!",
  // 51-60
  "Přijde muž do lékárny: Máte něco proti kašli? Lékárník: Ne, nemám nic proti kašli, klidně kašlete.",
  "Jaký je rozdíl mezi školou a válkou? Válka jednou skončí.",
  "Pepíček: Babičko, máš dobré oči? Babička: Mám. Pepíček: A proč nevidíš, že jím čokoládu?",
  "Co řekne jeden strom druhému na podzim? Listuj dál!",
  "Manželka: Miláčku, jsem krásná nebo chytrá? Manžel: Drahá, ty přece víš, že potřebuješ brýle.",
  "Přijde muž k lékaři: Doktore, všude mě to bolí. Když se dotknu hlavy, bolí to. Nohy taky. Ruka taky. Doktor: Máte zlomený prst.",
  "Co má osm noh a čeká na vhodný okamžik? Dva kluci před holčičí šatnou.",
  "Učitelka: Jak vzniká rosa? Pepíček: Země se otáčí tak rychle, že se potí!",
  "Proč ryby žijí ve slané vodě? Protože z pepře by kýchaly.",
  "Přijde muž do obchodu: Máte baterie? Kolik? Dva kusy. Tak si jich vezměte víc, jsou na záskok.",
  // 61-70
  "Co dělá ledňáček, když mu je zima? Nic, je zvyklý.",
  "Pepíček: Mami, všichni ve škole říkají, že se chlubím. Máma: A co jim říkáš? Pepíček: Že mám nejkrásnější maminku na světě!",
  "Proč se ve škole neučí o WiFi? Protože by to mělo příliš mnoho připojení.",
  "Dva kamarádi: Jsem v životě tam, kde jsem před 5 lety ani nečekal. Kde? Stále doma.",
  "Přijde žena do květinářství: Dejte mi kytici na pohřeb. Komu? Mému manželovi. A co spáchal? Přinesl mi květiny z benzínky.",
  "Co řekne nula osmičce? Pěkný opasek!",
  "Volá manžel: Zlato, auto nepojede, má vodu v karburátoru. Manželka: A kde je to auto? Manžel: V rybníce.",
  "Jaký je rozdíl mezi školním vysvědčením a Titanickem? Titanic měl aspoň tři trojky.",
  "Pepíček: Tati, jak to že sněhuláci nemají děti? Táta: Protože sněhulačky mají studenou hlavu.",
  "Přijde optimista k doktorovi: Doktore, já jsem zdravý! Doktor: To napravíme.",
  // 71-80
  "Co řekne matematik, když nemůže najít X? Kde je moje EX?",
  "Žena muži: Musíme si promluvit! Muž: O čem? Žena: O naší komunikaci! Muž: Jaké komunikaci?",
  "Pepíček ve škole: Paní učitelko, je pravda, že za něco, co jsem neudělal, nemohu dostat pětku? Učitelka: Ano. Pepíček: Super, neudělal jsem domácí úkol.",
  "Proč programátoři raději pracují v tmě? Protože bugs se bojí světla.",
  "Co řekne elektrický proud, když narazí do zdi? Watt?!",
  "Přijde muž do optiky: Potřebuji brýle. Optik: To vidím! Muž: Tak proč JÁ potřebuji brýle?",
  "Manžel: Vařila jsi někdy podle receptu? Manželka: Ano. Manžel: A čím to, že to nechutná jako v receptu? Manželka: Asi je špatný ten recept.",
  "Co má společného škola a pračka? Do obou se chodí neradi a z obou vycházíš zdrcený.",
  "Učitelka: Jaké znáš vodní sporty? Pepíček: Mytí nádobí!",
  "Dva kamarádi: Moje žena mě naučila co je trpělivost. A jak? Pořád mi to opakuje.",
  // 81-90
  "Přijde muž do obchodu: Kolik stojí ta televize? Prodavač: 15 tisíc. Muž: To je moc! A co ta vedle? Prodavač: To je mikrovlnka.",
  "Co řekne jeden komár druhému? Pojďme na párty, slyšel jsem, že jsou všichni v pyžamech!",
  "Pepíček: Tati, napiš mi do žákovské. Táta: Co mám napsat? Pepíček: Cokoliv, učitelka to stejně nepřečte.",
  "Proč se medvědi neholí? Protože se jim to nelíbí a nikdo se jim to neodváží říct.",
  "Doktor: Máte problém s alkoholem? Pacient: Ne, piju úplně bez problémů.",
  "Co říká jeden hrnek druhému? Drž hubu!",
  "Manželka: Víš co je dnes za den? Manžel nervózně: Samozřejmě! Manželka: Tak vynes koš, je středa.",
  "Přijde muž k sousedovi: Můžu si půjčit sekačku? Soused: Jasně, ale neodnášej ji daleko! Muž: Neboj, jen poseču váš trávník.",
  "Jaký je rozdíl mezi mozkem a žárovkou? Žárovce stačí jedna otočka.",
  "Co řekne šnek na hřbetě želvy? Jééé, to je jízda!",
  // 91-100
  "Pepíček: Mami, dneska mě učitelka pochválila! Máma: Vážně? Za co? Pepíček: Řekla: Pepíčku, ty jsi případ!",
  "Proč nesmí pes řídit auto? Protože by pořád dával packu z okna.",
  "Přijde muž do restaurace: Číšníku, v polévce mi plave moucha! Číšník: To je správně, umí plavat.",
  "Co řekne kalkulačka učiteli? Můžete na mě počítat!",
  "Manželka: Dneska jsem celý den uklízela! Manžel se rozhlédne: A kde?",
  "Učitelka: Kdo mi řekne příklad statické elektřiny? Pepíček: Účet za elektřinu, který leží na stole třetí měsíc.",
  "Přijde želva do baru: Jedno pivo prosím. Barman: Obdivuji vaši trpělivost, šel jste sem dvě hodiny. Želva: Zapomněla jsem peněženku, musím se vrátit.",
  "Co dělá informatik na zahradě? Hledá bugy.",
  "Dva kamarádi: Včera jsem běžel maraton! Celý? Ne, jen k ledničce a zpátky, ale třikrát.",
  "Jaký je rozdíl mezi WiFi a manželkou? WiFi se ke mně připojí automaticky, jakmile přijdu domů."
};

const int zalmyPocet = 100;
const char* zalmy[] = {
  "Hospodin je můj pastýř, nebudu míti nedostatku. – Žalm 23:1",
  "Bůh jest naše útočiště i síla, ve všelikém soužení pomoc hotová. – Žalm 46:1",
  "Smiluj se nade mnou, Bože, podlé milosrdenství svého. – Žalm 51:3",
  "Blahoslavený člověk, který se bojí Hospodina. – Žalm 112:1",
  "Všechno má určenou chvíli a veškeré dění pod nebem svůj čas. – Kazatel 3:1",
  "Důvěřuj Hospodinu celým srdcem, na svoji rozumnost nespoléhej. – Přísloví 3:5",
  "Neboj se, vždyť já jsem s tebou, já jsem tvůj Bůh. – Izajáš 41:10",
  "Neboť Bůh tak miloval svět, že dal svého jednorozeného Syna. – Jan 3:16",
  "Já jsem cesta, pravda i život. – Jan 14:6",
  "A tak zůstává víra, naděje a láska. Ale největší je láska. – 1. Kor 13:13",
  // 11-20
  "Hospodine, ty mě zkoumáš a znáš mě. – Žalm 139:1",
  "Chvalte Hospodina, všechny národy! – Žalm 117:1",
  "Hospodin je blízko všem, kteří ho vzývají. – Žalm 145:18",
  "Svěř Hospodinu svou cestu, doufej v něj a on bude jednat. – Žalm 37:5",
  "Hospodin je mé světlo a má spása, koho bych se bál? – Žalm 27:1",
  "Stvoř mi čisté srdce, Bože, a obnov ve mně ducha přímého. – Žalm 51:12",
  "Jako laň dychtí po tekoucí vodě, tak dychtí má duše po tobě, Bože. – Žalm 42:2",
  "Blaze tomu, z něhož je nevěrnost sňata. – Žalm 32:1",
  "Okuste a vizte, jak dobrý je Hospodin! – Žalm 34:9",
  "Hospodin je spravedlivý ve všech svých cestách. – Žalm 145:17",
  // 21-30
  "Byť se mi dostalo jíti údolím stínu smrti, nebudu se báti zlého. – Žalm 23:4",
  "Hospodin za mne dokoná. Tvé milosrdenství trvá navěky. – Žalm 138:8",
  "Rozpomeň se na slovo své k služebníku svému, na něž jsi mě čekati rozkázal. – Žalm 119:49",
  "Lepší je den v tvých nádvořích než jinde tisíc. – Žalm 84:11",
  "Z hlubin volám k tobě, Hospodine! – Žalm 130:1",
  "Nebesa vypravují o Boží slávě, obloha hovoří o díle jeho rukou. – Žalm 19:2",
  "Chválu vzdejte Hospodinu, protože je dobrý, jeho milosrdenství je věčné. – Žalm 136:1",
  "Hospodin kraluje, národy se třesou. – Žalm 99:1",
  "Požehnaný buď Hospodin den co den! – Žalm 68:20",
  "On uzdravuje ty, kdo mají srdce zkroušené. – Žalm 147:3",
  // 31-40
  "Já volám k Bohu a Hospodin mě spasí. – Žalm 55:17",
  "Budu zpívat Hospodinu po celý svůj život. – Žalm 104:33",
  "Tvé slovo je svíce mým nohám a světlo mé stezce. – Žalm 119:105",
  "Hrad přepevný jest Bůh náš. – Žalm 46:2",
  "Blaze lidu, jehož Bohem je Hospodin. – Žalm 33:12",
  "Pojďte, zpívejme Hospodinu s radostí! – Žalm 95:1",
  "Hospodin je dobrotivý ke všem a soucit má se vším, co učinil. – Žalm 145:9",
  "Já však budu vyhlížet k Hospodinu, čekat na Boha, svou spásu. – Micheáš 7:7",
  "Kdo vyslyší slovo a činí je, je jako moudrý muž. – Matouš 7:24",
  "Radujte se v Pánu vždycky, znovu říkám, radujte se! – Filipským 4:4",
  // 41-50
  "Pokoj vám zanechávám, svůj pokoj vám dávám. – Jan 14:27",
  "Já jsem s vámi po všechny dny až do skonání tohoto věku. – Matouš 28:20",
  "Proste, a bude vám dáno; hledejte, a naleznete. – Matouš 7:7",
  "Pojďte ke mně všichni, kdo se namáháte a jste obtíženi břemeny. – Matouš 11:28",
  "Já jsem ten dobrý pastýř. – Jan 10:11",
  "Milujte se navzájem, jako jsem já miloval vás. – Jan 15:12",
  "Láska je trpělivá, laskavá, nezávidí, láska se nevychloubá. – 1. Kor 13:4",
  "Víme, že těm, kdo milují Boha, všechno napomáhá k dobrému. – ��ímanům 8:28",
  "Žijte v lásce, tak jako Kristus miloval nás. – Efezským 5:2",
  "Všechnu svou starost vložte na něj, neboť mu na vás záleží. – 1. Petrův 5:7",
  // 51-60
  "Hospodin je síla má a píseň má, on je má spása. – Žalm 118:14",
  "Kdo žízní, ať přijde; kdo chce, ať zadarmo nabere vody života. – Zjevení 22:17",
  "Vy jste světlo světa. Nemůže se skrýt město ležící na hoře. – Matouš 5:14",
  "Jdi a už nehřeš. – Jan 8:11",
  "Já jsem chléb života. Kdo přichází ke mně, nikdy nebude hladovět. – Jan 6:35",
  "Neboj se, jen věř. – Marek 5:36",
  "Duch Hospodinův jest nade mnou. – Lukáš 4:18",
  "Jste-li vedeni Duchem, nejste pod zákonem. – Galatským 5:18",
  "Ovoce Ducha je láska, radost, pokoj, trpělivost, laskavost. – Galatským 5:22",
  "Buďte k sobě navzájem laskaví a milosrdní. – Efezským 4:32",
  // 61-70
  "Dej mi poznat své cesty, Hospodine, uč mě svým stezkám. – Žalm 25:4",
  "Hospodin je při mně, nebojím se. Co by mi mohl udělat člověk? – Žalm 118:6",
  "On dává zemdlenému sílu a vysílenému moc. – Izajáš 40:29",
  "Kdo vytrvá až do konce, bude spasen. – Matouš 24:13",
  "Neboj se malé stádce, neboť vašemu Otci se zalíbilo dát vám království. – Lukáš 12:32",
  "Buďte stálí, nedejte se zviklat, buďte horliví v Pánově díle. – 1. Kor 15:58",
  "Kdo je v Kristu, je nové stvoření. Co je staré, pominulo. – 2. Kor 5:17",
  "Mohu všecko v Kristu, který mi dává sílu. – Filipským 4:13",
  "Neboť kde jsou dva nebo tři shromážděni ve jménu mém, tam jsem já. – Matouš 18:20",
  "Hospodin tě bude střežit ode všeho zlého. – Žalm 121:7",
  // 71-80
  "Hledejte především Boží království a jeho spravedlnost. – Matouš 6:33",
  "Ten, kdo je ve vás, je větší než ten, kdo je ve světě. – 1. Jan 4:4",
  "Odpouštějte, a bude vám odpuštěno. – Lukáš 6:37",
  "Začátek moudrosti je bázeň před Hospodinem. – Přísloví 9:10",
  "Přijmi moudrost a tvůj život bude dobrý. – Přísloví 4:10",
  "Vlídná odpověď odvrací rozhořčení, kdežto slovo zraňující budí hněv. – Přísloví 15:1",
  "Hospodin je věrný ve všech svých slovech. – Žalm 145:13",
  "Bůh není Bohem zmatku, nýbrž Bohem pokoje. – 1. Kor 14:33",
  "Radostné srdce hojí rány, ale sklíčený duch vysušuje kosti. – Přísloví 17:22",
  "Lépe je málo se spravedlností než velké jmění s bezprávím. – Přísloví 16:8",
  // 81-90
  "Kdo chodí s moudrými, bude moudrý. – Přísloví 13:20",
  "Hospodin je blízko zkroušeným v srdci, na duchu zdeptané zachraňuje. – Žalm 34:19",
  "Kdo věří ve mne, i kdyby umřel, bude žít. – Jan 11:25",
  "Jestliže vyznáváme své hříchy, on je věrný a odpouští. – 1. Jan 1:9",
  "Bůh je láska. – 1. Jan 4:8",
  "Já vím, že můj Vykupitel je živ. – Jób 19:25",
  "Člověk se dívá na to, co má před očima, Hospodin však hledí na srdce. – 1. Sam 16:7",
  "Kdo je věrný v malém, je věrný i ve velkém. – Lukáš 16:10",
  "Cokoli děláte, dělejte to z celého srdce, jako Pánu. – Koloským 3:23",
  "Blaze těm, kdo jsou čistého srdce, neboť oni uzří Boha. – Matouš 5:8",
  // 91-100
  "Blaze těm, kdo působí pokoj, neboť budou nazváni syny Božími. – Matouš 5:9",
  "Já jsem vzkříšení a život. – Jan 11:25",
  "Pravda vás učiní svobodnými. – Jan 8:32",
  "Každý dobrý dar je shůry, sestupuje od Otce světel. – Jakub 1:17",
  "Hospodin je tvůj ochránce, Hospodin je tvůj stín po pravici. – Žalm 121:5",
  "Milost vám a pokoj od Boha. – Římanům 1:7",
  "Pojďte a uvidíte! – Jan 1:39",
  "Hospodin je dobrotivý, přímý. Proto ukazuje hříšným cestu. – Žalm 25:8",
  "Kdo spoléhá na Hospodina, je jako hora Sijón, jež se nepohne. – Žalm 125:1",
  "Chvalte Hospodina, neboť je dobrý, jeho milosrdenství je věčné! – Žalm 106:1"
};

const int citatyPocet = 100;
const char* citaty[] = {
  "Jediný způsob, jak dělat skvělou práci, je milovat to, co děláte. – Steve Jobs",
  "Budoucnost patří těm, kteří věří v krásu svých snů. – Eleanor Roosevelt",
  "Nejlepší čas zasadit strom byl před 20 lety. Druhý nejlepší je teď.",
  "Není důležité jak pomalu jdeš, hlavně že se nezastavíš. – Konfucius",
  "Každý člověk je tvůrcem svého osudu. – Sallustius",
  "Život je to, co se ti děje, zatímco plánuješ něco jiného. – John Lennon",
  "Buď změnou, kterou chceš vidět ve světě. – Mahátma Gándhí",
  "Úspěch není konečný, neúspěch není fatální. – Winston Churchill",
  "Vzdělání je nejmocnější zbraň, kterou můžeš změnit svět. – Nelson Mandela",
  "Štěstí není něco hotového. Přichází z tvých vlastních činů. – Dalajláma",
  // 11-20
  "Největší sláva není v tom nikdy nepadnout, ale v tom pokaždé vstát. – Konfucius",
  "Fantazie je důležitější než znalosti. – Albert Einstein",
  "Kdo se bojí udělat chybu, neudělá nikdy nic. – autor neznámý",
  "Cesta tisíce mil začíná jedním krokem. – Lao-c'",
  "To, co za sebou necháš, není to, co je vyryto do kamenných pomníků, ale co je vetkáno do životů druhých. – Perikles",
  "Není nic nemožného. Slovo samo říká: Jsem možný! – Audrey Hepburn",
  "Život se buď odvážně žije, nebo se žije naprázdno. – Helen Keller",
  "Chytrý se učí z chyb druhých, hloupý z vlastních. – české přísloví",
  "V jednoduchosti je krása. – Leonardo da Vinci",
  "Kdo chce, hledá způsoby. Kdo nechce, hledá důvody. – autor neznámý",
  // 21-30
  "Štěstí není cíl, je to způsob cestování. – Margaret Lee Runbeck",
  "Lidé zapomenou co jsi řekl, zapomenou co jsi udělal, ale nezapomenou jak se díky tobě cítili. – Maya Angelou",
  "Největší riziko je neriskovat vůbec. – Mark Zuckerberg",
  "Věř, že můžeš, a máš to z půlky za sebou. – Theodore Roosevelt",
  "Úspěch je součet malých snah opakovaných den co den. – Robert Collier",
  "Každý den je nový začátek. – T. S. Eliot",
  "Není důležité kolikrát spadneš, ale kolikrát vstaneš. – Vince Lombardi",
  "Lépe je být nenáviděn za to, kým jsi, než milován za to, kým nejsi. – André Gide",
  "Pořádek je pro hloupé. Génius ovládá chaos. – Albert Einstein",
  "Šťastný není ten, kdo má hodně, ale ten, komu stačí málo. – české přísloví",
  // 31-40
  "Lidský duch je silnější než cokoliv, co se mu může přihodit. – C. C. Scott",
  "Nepřestávej snít, protože ve snech je ukrytá brána k věčnosti. – Kahlil Gibran",
  "Kdo ovládá svůj hněv, je silnější než ten, kdo dobude město. – Šalamoun",
  "Každý velký sen začíná snílkem. – Harriet Tubman",
  "Nikdy se nevzdávej, protože právě to je místo a čas, kdy se věci změní. – Harriet Beecher Stowe",
  "Moudrý člověk mluví, protože má co říct. Hloupý, protože musí něco říct. – Platón",
  "Život shrne do několika okamžiků, které tě změní navždy. – autor neznámý",
  "Někdy správná cesta není ta nejlehčí. – Pocahontas",
  "Když ti život dá citrony, udělej si limonádu. – Elbert Hubbard",
  "Minulost nemůžeš změnit. Ale budoucnost je stále v tvých rukou. – autor neznámý",
  // 41-50
  "Dobrý přítel zná tvé příběhy. Nejlepší přítel je žil s tebou. – autor neznámý",
  "Svět je kniha a ti, kdo necestují, čtou jen jednu stránku. – sv. Augustin",
  "Žij tak, jako bys měl zemřít zítra. Uč se tak, jako bys měl žít věčně. – Mahátma Gándhí",
  "Není nic trvalejšího než dočasné řešení. – české přísloví",
  "Ten, kdo se ptá, je hlupák pět minut. Ten, kdo se neptá, zůstane hlupákem navždy. – čínské přísloví",
  "Odvaha není absence strachu, ale rozhodnutí, že něco je důležitější. – Ambrose Redmoon",
  "Nesuď dny podle sklizně, ale podle semen, která zaséváš. – Robert Louis Stevenson",
  "Tajemství úspěchu je začít. – Mark Twain",
  "Znalost bez praxe je jako loď na souši. – autor neznámý",
  "Nejlepší způsob jak předpovědět budoucnost je vytvořit ji. – Peter Drucker",
  // 51-60
  "Lidé jsou přesně tak šťastní, jak se rozhodnou být. – Abraham Lincoln",
  "Člověk, který nikdy neudělal chybu, nikdy nic nezkoušel. – Albert Einstein",
  "Krása zachrání svět. – Fjodor Dostojevskij",
  "Není silný vítr, který by neustále foukal. – české přísloví",
  "Někdy stačí jen jeden člověk, aby ti vrátil víru v lidi. – autor neznámý",
  "Skutečný přítel je ten, kdo přijde, když celý svět odejde. – Walter Winchell",
  "Každý člověk, kterého potkáš, bojuje boj, o kterém nic nevíš. Buď laskavý. – Platón",
  "Úspěch se měří tím, kolik překážek jsi překonal. – Booker T. Washington",
  "Nikdy neříkej nikdy, protože limity jako strachy jsou často jen iluze. – Michael Jordan",
  "Život není o tom čekat, až přejde bouřka, ale naučit se tančit v dešti. – Vivian Greene",
  // 61-70
  "Ztrácíš 100 % šancí, které nikdy nevyužiješ. – Wayne Gretzky",
  "Jedinou cestou ke skvělé práci je milovat to, co děláš. – Steve Jobs",
  "Buď sobě tím, čím chceš být pro ostatní. – autor neznámý",
  "Co tě nezabije, to tě posílí. – Friedrich Nietzsche",
  "Život je příliš krátký na to, abys byl někým jiným. – autor neznámý",
  "Slovo je stříbro, mlčení je zlato. – české přísloví",
  "Když se zavřou jedny dveře, otevřou se jiné. – Alexander Graham Bell",
  "Největší dobrodružství je žít. – autor neznámý",
  "Všechno, co potřebuješ, je na druhé straně strachu. – Jack Canfield",
  "Není problém udělat chybu. Problém je z ní se nepoučit. – autor neznámý",
  // 71-80
  "Ráno moudřejší večera. – české přísloví",
  "Kdo se směje naposled, ten se směje nejlíp. – české přísloví",
  "Bez práce nejsou koláče. – české přísloví",
  "Kdo jinému jámu kopá, sám do ní padá. – české přísloví",
  "Trpělivost růže přináší. – české přísloví",
  "Komu se nelení, tomu se zelení. – české přísloví",
  "Lepší vrabec v hrsti než holub na střeše. – české přísloví",
  "Kdo mlčí, souhlasí. – české přísloví",
  "Učení je stříbro, praxe je zlato. – autor neznámý",
  "Neodkládej na zítřek, co můžeš udělat dnes. – Benjamin Franklin",
  // 81-90
  "Vítězí ten, kdo se nevzdá. – autor neznámý",
  "Každý den ti dává příležitost být lepší než včera. – autor neznámý",
  "Smích je nejkratší vzdálenost mezi dvěma lidmi. – Victor Borge",
  "Pravá moudrost je vědět, že nic nevím. – Sokrates",
  "Činy mluví hlasitěji než slova. – Abraham Lincoln",
  "Síla není v tom nikdy nepadnout, ale vždy se zvednout. – Nelson Mandela",
  "Když nemůžeš změnit situaci, změň svůj přístup k ní. – Maya Angelou",
  "Vždycky je příliš brzy na to vzdát se. – Norman Vincent Peale",
  "Nejlepší investice je investice do sebe. – Warren Buffett",
  "Nikdo ti nemůže dát pocit méněcennosti bez tvého souhlasu. – Eleanor Roosevelt",
  // 91-100
  "Štěstí přeje připraveným. – Louis Pasteur",
  "Jsi silnější, než si myslíš, a odvážnější, než se cítíš. – A. A. Milne",
  "Největší chybou je bát se udělat chybu. – Elbert Hubbard",
  "Život je krátký. Usměj se, dokud máš zuby. – autor neznámý",
  "Dobré věci přicházejí k těm, kteří čekají, ale lepší věci k těm, kteří jdou a berou. – autor neznámý",
  "Jediný limit je ten, který si sám stanovíš. – autor neznámý",
  "Nevíme, jak silní jsme, dokud být silný není jedinou volbou. – Bob Marley",
  "Pokud nemáš co říct, řekni to s úsměvem. – autor neznámý",
  "Budoucnost závisí na tom, co děláš dnes. – Mahátma Gándhí",
  "Žij svůj život. Nikdo jiný to za tebe neudělá. – autor neznámý"
};

const int faktyPocet = 50;
const char* fakty[] = {
  "Lidský mozek má asi 86 miliard neuronů a každý z nich může být propojen s dalšími až 10 000 neurony.",
  "Med nikdy nezkazí. V egyptských hrobkách byl nalezen med starý 3 000 let, který byl stále jedlý.",
  "Chobotnice mají tři srdce a jejich krev je modrá díky hemocyaninu obsahujícímu měď.",
  "Světelný rok je vzdálenost, kterou světlo urazí za jeden rok — přibližně 9,46 bilionu kilometrů.",
  "Nejstarší strom na světě je Velká Basin bristlecone borovice v USA — je jí více než 5 000 let.",
  "Lidské tělo obsahuje přibližně 37 bilionů buněk.",
  "Voda tvoří asi 60 % lidského těla. Mozek a srdce jsou z 73 % voda.",
  "Blesk může dosáhnout teploty až 30 000 Kelvinů — pětkrát více než povrch Slunce.",
  "Kleopatra žila blíže v čase ke stavbě první pizzerie než ke stavbě pyramid.",
  "Včelí královna může žít až 5 let a denně snést až 2 000 vajíček.",
  "V lidském těle je více bakteriálních buněk než vlastních lidských buněk.",
  "Nejhlubší místo oceánu — Mariánský příkop — je hlubší než je vysoký Mount Everest.",
  "Oxford University je starší než aztécká říše — začala přijímat studenty před rokem 1096.",
  "Slon je jediné zvíře, které neumí skákat.",
  "Kolibřík je jediný pták, který dokáže létat dozadu.",
  "Slunce tvoří 99,86 % veškeré hmoty sluneční soustavy.",
  "Diamant je tvořen uhlíkem — stejně jako tužková tuha, jen jinak uspořádaným.",
  "Lidský jazyk je nejsilnějším svalem v těle v poměru ke své velikosti.",
  "Průměrný mrak váží přibližně 500 tun vody.",
  "Čínská zeď není z vesmíru viditelná pouhým okem — je moc úzká.",
  "Na Saturnových měsících Titan a Enceladus vědci předpokládají přítomnost kapalné vody.",
  "Šnek může spát až 3 roky v kuse.",
  "Lidský nos dokáže rozeznat přes bilion různých vůní.",
  "Každý rok přibude na Zemi asi 60 miliard kilogramů hmyzu.",
  "Měsíc se každý rok vzdaluje od Země přibližně o 3,8 centimetru.",
  "Zlatá rybka má paměť delší než 3 sekundy — ve skutečnosti si pamatuje věci i po měsících.",
  "Průměrný člověk stráví v životě přibližně 6 let snění.",
  "Želva může dýchat zadní částí těla — kloakou.",
  "Vesmír je starý přibližně 13,8 miliardy let.",
  "Kráva je schopna jít do schodů nahoru, ale ne dolů.",
  "Banány jsou mírně radioaktivní díky obsahu draslíku-40.",
  "Každý rok způsobí pády z kóje více smrtelných úrazů než žraloci — žraloci zabijí průměrně 6 lidí ročně.",
  "DNA jednoho člověka, natažená za sebou, by dosáhla od Země ke Slunci a zpět 300krát.",
  "Mravenci nikdy nespí a nemají plíce — dýchají trachejemi v celém těle.",
  "Blesk udeří do Země zhruba 100krát za sekundu — to je 8 milionů blesků denně.",
  "Naše Mléčná dráha má průměr asi 100 000 světelných let.",
  "Pokud byste mohli složit list papíru 42krát, dosáhl by výšky Měsíce.",
  "Jazyk žirafy je dlouhý asi 45 cm a je tmavě modrý.",
  "Každý rok se do oceánů dostanou 8 milionů tun plastů.",
  "Průměrný lidský mozek vytvoří přibližně 70 000 myšlenek za den.",
  "Teplota jádra Země je přibližně 5 100 °C — srovnatelná s povrchem Slunce.",
  "Slůně je schopno plavat od narození.",
  "Chobotnice má tři srdce, devět mozků a modrou krev.",
  "V atmosféře Venuše bylo zjištěno fosfin, což může naznačovat biologický původ.",
  "Průměrný člověk za svůj život ujde vzdálenost rovnající se třem cestám kolem Zeměkoule.",
  "Kočičí dotek uvolňuje v těle oxytocin — hormon štěstí.",
  "Pavouci vypijí ročně více hmyzu, než kolik vší lidské populace sní masa.",
  "Krevní skupina ovlivňuje, jak vás přitahují komáři — typ 0 je nejatraktivnější.",
  "Mars má dvě měsíce: Phobos a Deimos. Phobos se každým rokem přibližuje a za 50 milionů let se rozpadne.",
  "Veverky zapomínají, kde schovaly až 74 % žaludů, čímž nechtěně sázejí nové stromy."
};

#endif