#ifndef KNIHY_H
#define KNIHY_H

const char kniha1[] PROGMEM =
  "Geralt z Rivie seděl v temném koutě hostince a pomalu upíjel pivo. "
  "Venku zuřila bouře a blesky osvětlovaly mokré střechy města Vizima. "
  "Zaklínač přemýšlel o své poslední zakázce – obyvatelé vesnice Bykovice "
  "ho najali, aby zabil ghúla, který se usídlil na místním hřbitově. "
  "Práce to byla snadná, ale odměna bídná. Pár korun a džbán kyselého vína. "
  "Geralt si povzdechl. Takový je život zaklínače – nikdo tě nechce, dokud "
  "tě nepotřebuje. A když tě potřebují, stejně ti zaplatí co nejméně. "
  "Dveře hostince se rozlétly a dovnitř vešla žena s kapucí přes obličej. "
  "Přistoupila ke Geraltovu stolu a posadila se bez vyzvání. Pod kapucí "
  "se skrývaly fialové oči – Yennefer z Vengerbergu. Geralt málem spadl "
  "ze židle. Nebyla to příjemná návštěva. Naposledy se rozešli ve zlém "
  "a Geralt doufal, že ji nějakou dobu neuvidí. Yennefer si objednala "
  "víno a bez okolků řekla: Potřebuji tvou pomoc, zaklínači. V Temerii "
  "se dějí podivné věci. Lidé mizí z vesnic beze stopy. Stráže jsou "
  "bezmocné a král Foltest je zoufalý. Nabídl odměnu tisíc zlaťáků "
  "za vyřešení záhady. Geralt se napil piva a řekl: A proč právě já? "
  "Yennefer se usmála tím svým způsobem, který vždy znamenal potíže. "
  "Protože ty jsi jediný, kdo je dost hloupý, aby šel do Brokilonu "
  "hledat odpovědi. Geralt věděl, že má pravdu. Brokilonský les byl "
  "domovem dryadů a vstoupit tam bez pozvání znamenalo smrt. Ale tisíc "
  "zlaťáků by mu vystačilo na celou zimu v Kaer Morhen. Příští ráno "
  "vyrazili na cestu. Yennefer jela na koni a Geralt na své věrné Klepně. "
  "Cestou jim vyprávěla co zjistila – zmizelo už třicet lidí za poslední "
  "měsíc. Všichni z vesnic na okraji Brokilonu. Žádná těla, žádné stopy, "
  "žádní svědci. Jen prázdné domy a vyděšení sousedé. Geralt poslouchal "
  "a přemýšlel. Nebylo to typické pro žádnou příšeru, kterou znal. "
  "Dryady by nechaly těla jako varování. Vlkodlaci by zanechali krev. "
  "Tohle bylo něco jiného. Třetí den cesty dorazili k okraji Brokilonu. "
  "Les byl temný a tichý – ani ptáci nezpívali. Yennefer zastavila koně "
  "a řekla: Odtud musíme pěšky. A opatrně. Dryady nestřílí dvakrát. "
  "Geralt tasil meč a vstoupil do lesa. Každý strom vypadal jako strážce. "
  "Po hodině chůze našli první stopu – velký kruh spáleného mechu. "
  "Uprostřed kruhu byl symbol, který Geralt nikdy předtím neviděl. "
  "Yennefer zbledla. To je starší magie, zašeptala. Mnohem starší než "
  "čarodějové nebo elfové. Tohle je značka Divokého honu. "
  "Geralt věděl o Divokém honu jen z legend. Přízrační jezdci, kteří "
  "unášejí lidi do jiného světa. Pokud to byla pravda, vysvětlovalo by "
  "to zmizení vesničanů. Šli dál do hloubi lesa. Našli další kruhy, "
  "větší a silnější. Yennefer říkala, že magie zesiluje. Blížili se "
  "ke zdroji. Na mýtině uprostřed Brokilonu našli portál. Obrovský "
  "kruh z kamene, pulsující modrou energií. A kolem něj stáli lidé – "
  "zmizení vesničané! Byli v transu, nehybní jako sochy. Geralt chtěl "
  "přistoupit, ale Yennefer ho zastavila. Portál je střežený, řekla. "
  "Musíme najít kotvu – předmět, který ho drží otevřený. Hledali kolem "
  "a Geralt našel pod kamenem amulet s rudým krystalem. Když ho zvedl, "
  "portál se zachvěl. Z druhé strany se ozvalo řičení koní. Divoký hon "
  "se blížil! Yennefer rychle začala kouzlit ochranný štít. Geralt tasil "
  "oba meče. Z portálu vyjeli tři přízrační jezdci v ledové zbroji. "
  "Boj byl krátký ale zuřivý. Yennefer odrazila dva jezdce magií a Geralt "
  "zabil třetího stříbrným mečem. Amulet praskl a portál se zavřel. "
  "Vesničané se probudili z transu, zmatení ale živí. Vraceli se domů "
  "a Geralt s Yennefer je doprovázeli. Král Foltest zaplatil jak slíbil "
  "a Geralt měl konečně dost peněz na klidnou zimu. Ale věděl, že Divoký "
  "hon se vrátí. Vždycky se vrátí.";

const char kniha2[] PROGMEM =
  "Cesta do Oxenfurtu byla dlouhá a prašná. Marigold si neustále stěžoval "
  "na bolest nohou, horko a nedostatek kvalitního jídla. Geralt ho ignoroval "
  "tak, jak to dělával posledních deset let jejich přátelství. Na obzoru se "
  "objevily věže slavné oxenfurtské akademie a Marigold okamžitě ožil. "
  "Zde měl vystoupit na slavnosti letního slunovratu a doufal v tučný honorář. "
  "Geralt měl jiný cíl – hledal informace o čarodějce jménem Yennefer, která "
  "zmizela před třemi měsíci. Poslední zprávy o ní vedly právě sem, do města "
  "učenců a básníků. V akademické knihovně prý někdo viděl ženu s fialovýma očima. "
  "Geralt se ubytoval v hostinci U Alchymisty a vyrazil do knihovny. Starý "
  "knihovník si vzpomínal – ano, přišla žena, studovala staré svitky o portálech "
  "a dimenzích. Odešla před týdnem směrem na sever. Geralt poděkoval a vrátil se "
  "do hostince, kde Marigold už zpíval svou novou baladu o zaklínači a jednorožci. "
  "Hosté byli nadšení, ale Geralt se ušklíbl – ta historka se nikdy nestala. "
  "Ráno vyrazili na sever. Cesta vedla přes Pontar a do nilfgaardských území. "
  "Na hranici je zastavila hlídka. Nilfgaardský důstojník si prohlédl Geraltův "
  "medailon a řekl: Zaklínač. Slyšel jsem o vás. Máme problém s baziliškem "
  "u vesnice Bílý Sad. Vyřešte to a pustíme vás dál. Geralt neměl na výběr. "
  "Bazilišek žil ve zříceninách starého hradu. Byl obrovský – tři metry vysoký "
  "s jedovatým dechem. Geralt si připravil olej Zlatý oriole a lektvar Blesk. "
  "Boj trval půl hodiny. Bazilišek byl rychlý, ale Geralt rychlejší. Nakonec "
  "mu usekl hlavu a přinesl ji důstojníkovi. Ten splnil slib a pustil je dál. "
  "Za Pontarem krajina změnila ráz. Pole byla vypálená, vesnice prázdné. Válka "
  "se tu podepsala na každém kameni. Marigold přestal vtipkovat a tiše šel vedle "
  "Geralta. Po třech dnech dorazili do městečka Bílý Most. Tady stopa Yennefer "
  "končila. Hostinský řekl, že žena s fialovýma očima odjela s karavanou kupců "
  "směrem do hor. Geralt se rozhodl pokračovat. V horách našel opuštěný tábor. "
  "Yennefer tu byla – její magická stopa byla silná. Ale taky tu byla stopa "
  "něčeho jiného. Něčeho temného. Geralt prozkoumala tábor a našel deník. "
  "Yennefer psala o experimentu – snažila se otevřít portál do jiné dimenze "
  "aby našla lék na zaklínačskou neplodnost. Chtěla mít dítě. Geralt sevřel "
  "deník a pokračoval po stopě. Za táborem vedla úzká horská stezka k jeskyni. "
  "Uvnitř hořely svíce a na zemi byly magické kruhy. Yennefer ležela uprostřed "
  "v bezvědomí. Portál nad ní blikal nestabilně. Geralt ji vzal do náruče a "
  "odnesl pryč. Portál se zhroutil za nimi. Yennefer se probudila po třech dnech. "
  "Byla slabá, ale živá. Experiment selhal, ale ona žila. A to bylo to jediné, "
  "na čem Geraltovi záleželo. Vrátili se do Oxenfurtu, kde Marigold mezitím "
  "vyhrál pěveckou soutěž a byl slavný. Geralt si dal pivo a přemýšlel o tom, "
  "že některé věci nelze změnit magií. Ale lásku možná ano.";

const char kniha3[] PROGMEM =
  "Kaer Morhen stálo tiše a opuštěné jako vždy v zimních měsících. Sníh pokrýval "
  "nádvoří a vítr hvízdal mezi rozpadlými hradbami. Geralt, Eskel a Lambert "
  "seděli u krbu a popíjeli pálenku. Vesemir odešel spát již před hodinou. "
  "Tři zaklínači vzpomínali na staré časy, kdy tady bylo plno mladých adeptů "
  "a chodby zněly křikem výcviku. Teď zbyli jen oni – poslední svého druhu. "
  "Lambert jako obvykle začal vyprávět historky o svých dobrodružstvích a Eskel "
  "jen tiše poslouchal. Geralt přemýšlel o Ciri a kde asi teď může být. "
  "Venku zavyl vlk a plameny v krbu zaplápolaly ve studeném průvanu. "
  "Ráno přijel posel. Přivezl dopis od Triss Merigold. Psala, že se v Novigradě "
  "dějí podivné věci – čarodějky jsou pronásledovány a upalovány na hranicích. "
  "Chrám Věčného ohně vyhlásil hon na všechny uživatele magie. Triss prosila "
  "o pomoc. Geralt ukázal dopis ostatním. Lambert řekl: To není náš problém. "
  "Eskel mlčel. Vesemir si přečetl dopis dvakrát a pak řekl: Jednou z těch "
  "čarodějek mohla být tvoje Yennefer, Geralte. Nebo Ciri. Geralt věděl, že "
  "Vesemir má pravdu. Příští den vyrazil na cestu do Novigradu. Cesta z Kaer "
  "Morhen trvala dva týdny. Geralt cestoval přes Kaedwen, Redanii a nakonec "
  "dorazil k branám největšího města na kontinentu. Novigrad byl přelidněný, "
  "hlučný a smrdutý. Na každém rohu stáli kněží Věčného ohně a kázali proti "
  "magii. Na náměstí hořely hranice. Geralt našel Triss v úkrytu pod městem. "
  "Vypadala vyčerpaně. Vyprávěla mu o síti podzemních úkrytů, kde se schovávají "
  "čarodějky a nelidé. Elfové, trpaslíci, půlčíci – všichni byli v ohrožení. "
  "Geralt se rozhodl pomoci. Během následujících týdnů organizoval útěky. "
  "Převáděl čarodějky a nelidé na lodě směřující do Koviru, kde byli v bezpečí. "
  "Bylo to nebezpečné – stráže hlídkovaly všude a odměna za udání byla vysoká. "
  "Jednou je málem chytili. Geralt musel bojovat se šesti strážemi v úzké uličce. "
  "Zvládl to, ale jeden ze strážců utekl. Museli rychle změnit úkryt. Triss "
  "přesunula všechny do starých trpasličích katakomb pod městem. Tam byli "
  "v bezpečí, alespoň prozatím. Geralt se dozvěděl, že za honem na čarodějky "
  "stojí Radovid, redanijský král. Paranoidní tyran, který viděl spiknutí "
  "všude kolem sebe. Geralt přemýšlel, jestli by měl problém vyřešit u kořene. "
  "Ale zabít krále nebylo v popisu jeho práce. Nakonec se podařilo evakuovat "
  "většinu ohrozených. Triss odjela s poslední lodí. Na přídi stála a mávala "
  "Geraltovi. Ten stál na molu a díval se, jak loď mizí za obzorem. Pak se "
  "otočil a šel. Další práce čekala. Vždycky čekala.";

const char* knihy[] = {kniha1, kniha2, kniha3};

#endif