#ifndef SLOVNIK_H
#define SLOVNIK_H

struct SlovnikSlovo {
  const char* cz;
  const char* en;
};

const SlovnikSlovo slovnikData[] PROGMEM = {
  // === A ===
  {"a","and"},{"aby","in order to"},{"ale","but"},{"ani","neither"},
  {"ano","yes"},{"auto","car"},{"autobus","bus"},{"až","until"},
  {"anketa","survey"},{"opatrný","careful"},{"armáda","army"},{"asi","maybe"},
  {"atletika","athletics"},{"avšak","however"},{"aktuální","current"},
  {"americký","American"},{"anglický","English"},{"atmosféra","atmosphere"},
  {"atom","atom"},{"akce","event"},{"adresa","address"},{"Afrika","Africa"},
  {"alkohol","alcohol"},{"alergie","allergy"},{"ananas","pineapple"},
  {"apartment","apartment"},{"aplikace","application"},{"architekt","architect"},
  {"argument","argument"},{"asistent","assistant"},{"asociace","association"},
  {"audit","audit"},{"autor","author"},{"automat","machine"},{"avokádo","avocado"},
  {"azyl","asylum"},{"abeceda","alphabet"},{"absolvent","graduate"},{"absorpce","absorption"},
  {"abstraktní","abstract"},{"absurdní","absurd"},{"achát","agate"},{"adaptace","adaptation"},
  {"administrativa","administration"},{"adopce","adoption"},{"advent","advent"},
  {"aerobik","aerobics"},{"agenda","agenda"},{"agrese","aggression"},{"akademie","academy"},
  {"akce","action"},{"aktivita","activity"},{"aktivní","active"},{"akumulátor","accumulator"},
  {"alarm","alarm"},{"album","album"},{"alter","alter"},{"alternativa","alternative"},
  {"ambulance","ambulance"},{"analýza","analysis"},{"anděl","angel"},{"animace","animation"},
  {"apartmán","suite"},{"apetit","appetite"},{"aréna","arena"},{"artikl","item"},
  {"aspekt","aspect"},{"atlet","athlete"},{"atrakce","attraction"},{"automobil","automobile"},
  // === B ===
  {"babička","grandmother"},{"banka","bank"},{"barva","color"},{"bát se","to be afraid"},
  {"bez","without"},{"běžet","to run"},{"bezpečný","safe"},{"bílý","white"},
  {"blízko","near"},{"blízký","close"},{"blázen","fool"},{"bod","point"},
  {"bohužel","unfortunately"},{"boj","fight"},{"bolest","pain"},{"bohatý","rich"},
  {"boží","divine"},{"brána","gate"},{"bratr","brother"},{"brzy","soon"},
  {"brýle","glasses"},{"budova","building"},{"budoucnost","future"},{"být","to be"},
  {"bydlet","to live"},{"břeh","shore"},{"bzučák","buzzer"},{"baterie","battery"},
  {"bavit se","to have fun"},{"bedna","box"},{"benzín","gasoline"},{"beseda","discussion"},
  {"bezdomovec","homeless person"},{"bezpečnost","safety"},{"běžný","common"},
  {"bible","bible"},{"bicykl","bicycle"},{"biologie","biology"},{"biskup","bishop"},
  {"bít","to beat"},{"blaho","bliss"},{"bláto","mud"},{"bledý","pale"},
  {"blesk","lightning"},{"blízkost","proximity"},{"blok","block"},{"bloudit","to wander"},
  {"blues","blues"},{"bobr","beaver"},{"boční","side"},{"bodlák","thistle"},
  {"bohatství","wealth"},{"bolestivý","painful"},{"bomba","bomb"},{"bonbon","candy"},
  {"botanika","botany"},{"bota","shoe"},{"bouřka","storm"},{"bránit","to defend"},
  {"brambora","potato"},{"bratrský","brotherly"},{"brčko","straw"},{"brigáda","part-time job"},
  {"brouk","beetle"},{"brusinka","cranberry"},{"brutální","brutal"},{"březen","March"},
  {"břicho","belly"},{"budík","alarm clock"},{"budoucí","future"},{"bufet","buffet"},
  {"burza","stock exchange"},{"buňka","cell"},{"bůh","god"},{"bydliště","residence"},
  {"bystrý","sharp"},{"byt","apartment"},{"bytost","being"},{"bývalý","former"},
  // === C ===
  {"celý","whole"},{"cena","price"},{"cesta","way"},{"cíl","goal"},
  {"cítit","to feel"},{"cizí","foreign"},{"co","what"},{"cvičení","exercise"},
  {"centrum","center"},{"církev","church"},{"čaj","tea"},{"čas","time"},
  {"část","part"},{"často","often"},{"člověk","human"},{"černý","black"},
  {"červený","red"},{"český","Czech"},{"číst","read"},{"číslo","number"},
  {"čistý","clean"},{"článek","article"},{"čokoláda","chocolate"},{"čtvrtek","Thursday"},
  {"cukr","sugar"},{"cyklus","cycle"},{"celek","whole"},{"celkem","altogether"},
  {"celní","customs"},{"cements","cement"},{"cenný","valuable"},{"cestovat","to travel"},
  {"cestovatel","traveler"},{"cestující","passenger"},{"cibule","onion"},{"cigareta","cigarette"},
  {"cihla","brick"},{"cinkot","clinking"},{"citlivý","sensitive"},{"citron","lemon"},
  {"civilizace","civilization"},{"cizinec","foreigner"},{"clona","aperture"},
  {"cop","braid"},{"coukat","to back up"},{"cvik","exercise move"},
  {"čáp","stork"},{"čáska","comma"},{"čekat","to wait"},{"čelo","forehead"},
  {"čerpadlo","pump"},{"čerstvý","fresh"},{"červen","June"},{"červenec","July"},
  {"česnek","garlic"},{"čest","honor"},{"četba","reading"},{"či","or"},
  {"čin","act"},{"činnost","activity"},{"čistit","to clean"},{"člen","member"},
  {"členství","membership"},{"čočka","lens"},{"čtení","reading"},{"čtrnáct","fourteen"},
  {"čtverec","square"},{"čtvrt","quarter"},{"čtvrtina","quarter"},{"čtyři","four"},
  // === D ===
  {"dál","further"},{"další","next"},{"dárek","gift"},{"dát","to give"},
  {"datum","date"},{"dcera","daughter"},{"dělat","to do"},{"den","day"},
  {"déšť","rain"},{"deset","ten"},{"děkuji","thank you"},{"dětský","childrens"},
  {"díky","thanks"},{"díl","part"},{"dítě","child"},{"divadlo","theater"},
  {"dívat se","to watch"},{"dívka","girl"},{"dlouhý","long"},{"dnes","today"},
  {"dno","bottom"},{"do","to"},{"doba","era"},{"dobrý","good"},
  {"doktor","doctor"},{"dolů","down"},{"doma","at home"},{"domů","home"},
  {"dopis","letter"},{"doprava","transport"},{"dostat","to get"},{"dost","enough"},
  {"dotaz","question"},{"doufat","to hope"},{"drát","wire"},{"drahý","expensive"},
  {"druhý","second"},{"dřevo","wood"},{"důležitý","important"},{"důvod","reason"},
  {"dva","two"},{"dvacet","twenty"},{"dveře","door"},{"dvojice","pair"},
  {"dialekt","dialect"},{"daň","tax"},{"darovat","to donate"},
  {"dávat","to give"},{"dávka","dose"},{"dávno","long ago"},{"debata","debate"},
  {"definice","definition"},{"dekorace","decoration"},{"delegace","delegation"},
  {"dělník","worker"},{"demokracie","democracy"},{"demonstrace","demonstration"},
  {"deprese","depression"},{"design","design"},{"destička","board"},{"detail","detail"},
  {"detektiv","detective"},{"devatenáct","nineteen"},{"devět","nine"},{"devadesát","ninety"},
  {"Dialog","dialogue"},{"diamant","diamond"},{"dieta","diet"},{"digitální","digital"},
  {"dimenze","dimension"},{"diplom","diploma"},{"disciplína","discipline"},
  {"diskuse","discussion"},{"divák","spectator"},{"divoký","wild"},{"dlažba","pavement"},
  {"dluh","debt"},{"dnešní","todays"},{"dno","bottom"},{"dob","period"},
  {"dobrodružství","adventure"},{"dobrovolný","voluntary"},{"dobytek","cattle"},
  {"dočasný","temporary"},{"dodávat","to supply"},{"dodávka","delivery"},
  {"dohoda","agreement"},{"dojem","impression"},{"doklad","document"},
  {"dokonce","even"},{"dokončit","to finish"},{"dokument","document"},
  {"dolní","lower"},{"domácí","domestic"},{"domácnost","household"},
  {"dominantní","dominant"},{"domov","home"},{"donést","to bring"},
  {"doplnit","to supplement"},{"doporučit","to recommend"},{"dopředu","forward"},
  {"dort","cake"},{"dosáhnout","to achieve"},{"dospělý","adult"},
  {"dostačující","sufficient"},{"dostupný","available"},{"dotknout se","to touch"},
  {"dovnitř","inside"},{"dovolená","vacation"},{"dovolit","to allow"},
  {"drak","dragon"},{"drama","drama"},{"dráha","track"},{"drobný","tiny"},
  {"droga","drug"},{"drsný","rough"},{"druh","species"},{"družstvo","cooperative"},
  {"držet","to hold"},{"dub","oak"},{"duben","April"},{"duha","rainbow"},
  {"duch","spirit"},{"důchod","pension"},{"důkaz","proof"},{"důl","mine"},
  {"důstojný","dignified"},{"důvěra","trust"},{"důvěrný","confidential"},
  {"dvakrát","twice"},{"dvanáct","twelve"},{"dvouletý","two-year-old"},
  {"dýchat","to breathe"},{"dým","smoke"},{"dynamický","dynamic"},
  // === E ===
  {"ekonomika","economy"},{"elektřina","electricity"},{"energie","energy"},
  {"Evropa","Europe"},{"existovat","to exist"},{"experiment","experiment"},
  {"expert","expert"},{"exprese","express"},{"elastický","elastic"},
  {"elegantní","elegant"},{"elektronika","electronics"},{"emoce","emotion"},
  {"epocha","epoch"},{"etapa","stage"},{"evoluce","evolution"},{"extrém","extreme"},
  {"edice","edition"},{"efekt","effect"},{"efektivní","effective"},{"egyptský","Egyptian"},
  {"ekologie","ecology"},{"ekologický","ecological"},{"ekonom","economist"},
  {"ekonomický","economic"},{"elegance","elegance"},{"elektráren","power plant"},
  {"elektrický","electric"},{"element","element"},{"eliminovat","to eliminate"},
  {"emailovat","to email"},{"emigrace","emigration"},{"emise","emission"},
  {"emotivní","emotional"},{"empatie","empathy"},{"encyklopedie","encyclopedia"},
  {"energetický","energetic"},{"epizoda","episode"},{"erupce","eruption"},
  {"esej","essay"},{"estetický","aesthetic"},{"etický","ethical"},{"etika","ethics"},
  {"evidence","records"},{"evidentní","evident"},{"excelentní","excellent"},
  {"exil","exile"},{"exkluzivní","exclusive"},{"expandovat","to expand"},
  {"expedice","expedition"},{"exploze","explosion"},{"export","export"},
  {"expozice","exposure"},{"extravagantní","extravagant"},{"extrémní","extreme"},
  // === F ===
  {"fakt","fact"},{"fakulta","faculty"},{"fantazie","fantasy"},{"farma","farm"},
  {"film","film"},{"firma","company"},{"forma","form"},{"fotbal","football"},
  {"fotka","photo"},{"fungovat","to work"},{"fyzika","physics"},{"fialový","purple"},
  {"filozofie","philosophy"},{"festival","festival"},{"fikce","fiction"},{"finance","finance"},
  {"fabrika","factory"},{"fáze","phase"},{"fenomén","phenomenon"},{"figurka","figure"},
  {"filtr","filter"},{"finále","final"},{"finanční","financial"},{"fixní","fixed"},
  {"flaška","bottle"},{"flexibilní","flexible"},{"florbal","floorball"},{"fokus","focus"},
  {"fond","fund"},{"formální","formal"},{"formát","format"},{"formulář","form"},
  {"fosilie","fossil"},{"fotografie","photography"},{"fotograf","photographer"},
  {"foyer","foyer"},{"fragment","fragment"},{"frank","franc"},{"frekvence","frequency"},
  {"fronta","queue"},{"frustrace","frustration"},{"funkce","function"},
  {"funkční","functional"},{"fúze","fusion"},{"fyzický","physical"},
  // === G ===
  {"galerie","gallery"},{"garáž","garage"},{"gesto","gesture"},{"graf","graph"},
  {"gramotnost","literacy"},{"grupa","group"},{"guláš","goulash"},
  {"generace","generation"},{"génius","genius"},{"geografie","geography"},
  {"generál","general"},{"gól","goal"},{"gotický","gothic"},{"gratulovat","to congratulate"},
  {"gravitace","gravity"},{"gril","grill"},{"guma","rubber"},{"gymnázium","high school"},
  // === H ===
  {"had","snake"},{"hádat","to guess"},{"hasiči","firefighters"},{"heslo","password"},
  {"hezký","pretty"},{"historie","history"},{"hlad","hunger"},{"hlasitý","loud"},
  {"hlava","head"},{"hlavní","main"},{"hledat","to search"},{"hloupý","stupid"},
  {"hluboký","deep"},{"hmota","matter"},{"hned","immediately"},{"hnědý","brown"},
  {"hodina","hour"},{"hodně","a lot"},{"hodnota","value"},{"holka","girl"},
  {"hora","mountain"},{"horký","hot"},{"horní","upper"},{"hospoda","pub"},
  {"host","guest"},{"hotel","hotel"},{"hra","game"},{"hrad","castle"},
  {"hrana","edge"},{"hrát","to play"},{"hrdina","hero"},{"hrom","thunder"},
  {"hrozný","terrible"},{"hrubý","rough"},{"hruška","pear"},{"hřbitov","cemetery"},
  {"hudba","music"},{"humor","humor"},{"hvězda","star"},
  {"hádanka","riddle"},{"halíř","penny"},{"hanba","shame"},{"harmonika","accordion"},
  {"háček","hook"},{"hektický","hectic"},{"helma","helmet"},{"herec","actor"},
  {"herečka","actress"},{"hezky","nicely"},{"hierarchie","hierarchy"},
  {"hlášení","announcement"},{"hlas","voice"},{"hlasování","voting"},
  {"hlavně","mainly"},{"hlavolam","puzzle"},{"hlemýžď","snail"},
  {"hlídat","to guard"},{"hlína","clay"},{"hluk","noise"},{"hmat","touch"},
  {"hmotnost","weight"},{"hmyz","insect"},{"hněv","anger"},{"hnis","pus"},
  {"hnízdo","nest"},{"hodinky","watch"},{"hodiny","clock"},{"hodlat","to intend"},
  {"hodnost","rank"},{"hokej","hockey"},{"holit","to shave"},{"holub","pigeon"},
  {"hořet","to burn"},{"hořký","bitter"},{"horko","heat"},{"horlivý","zealous"},
  {"horník","miner"},{"horolezec","climber"},{"horoskop","horoscope"},
  {"horší","worse"},{"hospodář","farmer"},{"hospodářství","economy"},
  {"hostina","feast"},{"hotový","ready"},{"houba","mushroom"},{"houska","roll"},
  {"housle","violin"},{"hovno","crap"},{"hrabě","count"},{"hrách","pea"},
  {"hradba","rampart"},{"hranice","border"},{"hravý","playful"},{"hrdinství","heroism"},
  {"hrdlo","throat"},{"hrdost","pride"},{"hrnec","pot"},{"hrnek","mug"},
  {"hrobka","tomb"},{"hromada","pile"},{"hrozba","threat"},{"hrozit","to threaten"},
  {"hrozen","grape"},{"hrůza","horror"},{"hřbet","back"},{"hřeb","nail"},
  {"hřebík","nail"},{"hřích","sin"},{"hřiště","playground"},{"hub","mushroom"},
  {"hubený","skinny"},{"hulit","to smoke"},{"humanitní","humanitarian"},
  {"hustý","thick"},{"hvězdárna","observatory"},{"hygiena","hygiene"},{"hymna","anthem"},
  // === CH ===
  {"chalupa","cottage"},{"chápat","to understand"},{"chemie","chemistry"},
  {"chléb","bread"},{"chlapec","boy"},{"chladný","cold"},{"chodit","to walk"},
  {"chovat se","to behave"},{"chtít","to want"},{"chudý","poor"},
  {"chutnat","to taste"},{"chyba","mistake"},{"chytrý","smart"},
  {"chránit","to protect"},{"chvíle","moment"},
  {"charakteristika","characteristic"},{"charita","charity"},{"chat","cottage"},
  {"chemický","chemical"},{"chirurg","surgeon"},{"chladnička","fridge"},
  {"chlap","man"},{"chlupatý","hairy"},{"chmel","hops"},{"chodba","corridor"},
  {"chodec","pedestrian"},{"chodník","sidewalk"},{"choroba","disease"},
  {"chování","behavior"},{"chovatel","breeder"},{"chrám","cathedral"},
  {"chrápat","to snore"},{"chřest","asparagus"},{"chřipka","flu"},
  {"chtíč","lust"},{"chuť","taste"},{"chůze","walking"},{"chválit","to praise"},
  {"chystat","to prepare"},{"chytit","to catch"},
  // === I ===
  {"ideální","ideal"},{"ihned","immediately"},{"informace","information"},
  {"inteligentní","intelligent"},{"internet","internet"},{"investice","investment"},
  {"inženýr","engineer"},{"ironie","irony"},{"izolace","isolation"},
  {"inspirace","inspiration"},{"instituce","institution"},{"instrument","instrument"},
  {"identita","identity"},{"ignorovat","to ignore"},{"ikona","icon"},
  {"ilegální","illegal"},{"ilustrace","illustration"},{"imitace","imitation"},
  {"imigrant","immigrant"},{"imunita","immunity"},{"index","index"},
  {"individuální","individual"},{"infekce","infection"},{"inflace","inflation"},
  {"infrastruktura","infrastructure"},{"iniciativa","initiative"},{"inovace","innovation"},
  {"inscenace","staging"},{"instalace","installation"},{"instinkt","instinct"},
  {"integrace","integration"},{"intenzivní","intensive"},{"interakce","interaction"},
  {"interiér","interior"},{"interpretace","interpretation"},{"interval","interval"},
  {"intimní","intimate"},{"inventář","inventory"},{"investor","investor"},
  {"inzerát","advertisement"},{"ironický","ironic"},{"italský","Italian"},
  // === J ===
  {"já","I"},{"jablko","apple"},{"jahoda","strawberry"},{"jak","how"},
  {"jako","like"},{"jasný","clear"},{"jazyk","language"},{"jeden","one"},
  {"jednoduchý","simple"},{"jed","poison"},{"jeho","his"},{"její","her"},
  {"jen","only"},{"jenom","just"},{"jeskyně","cave"},{"jestli","if"},
  {"ještě","still"},{"jet","to go"},{"jezero","lake"},{"jídlo","food"},
  {"jih","south"},{"jinak","otherwise"},{"jiný","other"},{"jistý","certain"},
  {"jít","to go"},{"jízdné","fare"},{"jméno","name"},{"jmenovat se","to be called"},
  {"jabloň","apple tree"},{"jaderný","nuclear"},{"jáma","pit"},{"jantar","amber"},
  {"jaro","spring"},{"jasnozřivý","clairvoyant"},{"jatka","slaughterhouse"},
  {"javor","maple"},{"javorový","maple"},{"ječmen","barley"},{"jedináček","only child"},
  {"jedině","only"},{"jedinečný","unique"},{"jediný","sole"},{"jednání","negotiation"},
  {"jednat","to act"},{"jednička","number one"},{"jednodušše","simply"},
  {"jednota","unity"},{"jednotka","unit"},{"jednotlivý","individual"},
  {"jednou","once"},{"jehla","needle"},{"jehně","lamb"},{"jelen","deer"},
  {"jemný","gentle"},{"jeřáb","crane"},{"jesle","nursery"},{"jev","phenomenon"},
  {"jeviště","stage"},{"jezdit","to ride"},{"jezdec","rider"},{"jídelna","dining room"},
  {"jídelní","dining"},{"jídlo","meal"},{"jílovitý","clayey"},{"jinde","elsewhere"},
  {"jiskra","spark"},{"jistota","certainty"},{"jízda","ride"},{"jízdní","riding"},
  {"jogurt","yogurt"},{"junák","scout"},
  // === K ===
  {"kabát","coat"},{"kafe","coffee"},{"kam","where to"},{"kámen","stone"},
  {"kamarád","friend"},{"kapela","band"},{"kapsa","pocket"},{"karta","card"},
  {"každý","every"},{"kde","where"},{"kdo","who"},{"kdy","when"},
  {"kdybych","if I"},{"když","when"},{"klid","calm"},{"klíč","key"},
  {"klient","client"},{"kluk","boy"},{"kněz","priest"},{"kniha","book"},
  {"knihovna","library"},{"kolem","around"},{"koleno","knee"},{"kolik","how much"},
  {"kolo","bike"},{"koncert","concert"},{"konec","end"},{"konečně","finally"},
  {"kontakt","contact"},{"kontrola","control"},{"kopec","hill"},{"koruna","crown"},
  {"kostel","church"},{"košile","shirt"},{"kočka","cat"},{"koupelna","bathroom"},
  {"koupit","to buy"},{"kouřit","to smoke"},{"kozel","goat"},{"krajina","landscape"},
  {"král","king"},{"krása","beauty"},{"krásný","beautiful"},{"krátký","short"},
  {"krev","blood"},{"kritika","criticism"},{"krk","neck"},{"kromě","except"},
  {"kronika","chronicle"},{"krok","step"},{"kuchyně","kitchen"},{"kultura","culture"},
  {"kůň","horse"},{"kupovat","to buy"},{"kus","piece"},{"kvalita","quality"},
  {"květ","flower"},{"květen","May"},{"kvůli","because of"},
  {"kabelka","handbag"},{"kabina","cabin"},{"kadidlo","incense"},{"kalamita","calamity"},
  {"kalkulačka","calculator"},{"kamion","truck"},{"kampaň","campaign"},{"kanál","canal"},
  {"kancelář","office"},{"kandidát","candidate"},{"kapacita","capacity"},{"kapitán","captain"},
  {"kapitola","chapter"},{"kapka","drop"},{"kaple","chapel"},{"kapusta","cabbage"},
  {"karamel","caramel"},{"kariéra","career"},{"karta","card"},{"kartáč","brush"},
  {"karton","cardboard"},{"kasa","cash register"},{"kasárna","barracks"},{"kastrol","saucepan"},
  {"katalog","catalog"},{"katastrofa","catastrophe"},{"kategorie","category"},
  {"katedra","department"},{"katedrála","cathedral"},{"kavárna","cafe"},{"kazatel","preacher"},
  {"kazit","to spoil"},{"kelímek","cup"},{"kemp","camp"},{"keramika","ceramics"},
  {"kilometr","kilometer"},{"kino","cinema"},{"klasický","classical"},{"klášter","monastery"},
  {"klávesnice","keyboard"},{"klenot","jewel"},{"kleště","pliers"},{"klika","handle"},
  {"klima","climate"},{"klobouk","hat"},{"kloub","joint"},{"klub","club"},
  {"kmen","tribe"},{"kmotr","godfather"},{"knedlík","dumpling"},{"kníže","prince"},
  {"kobalt","cobalt"},{"koberec","carpet"},{"kočár","carriage"},{"kohoutek","tap"},
  {"kojenec","infant"},{"kolaps","collapse"},{"kolega","colleague"},{"kolej","dormitory"},
  {"kolekce","collection"},{"kolize","collision"},{"koloběh","cycle"},{"kolonie","colony"},
  {"kombinace","combination"},{"kometa","comet"},{"komfort","comfort"},
  {"komik","comedian"},{"komise","commission"},{"komnata","chamber"},{"komunita","community"},
  {"koncentrace","concentration"},{"koncept","concept"},{"kondice","fitness"},
  {"konference","conference"},{"konflikt","conflict"},{"konkrétní","specific"},
  {"konkurence","competition"},{"konstrukce","construction"},{"konzultace","consultation"},
  {"kopie","copy"},{"koření","spice"},{"korespondence","correspondence"},
  {"korupce","corruption"},{"kořen","root"},{"kostra","skeleton"},
  {"kostým","costume"},{"košík","basket"},{"kotva","anchor"},{"kouř","smoke"},
  {"kouzlo","magic"},{"kovář","blacksmith"},{"kozí","goats"},{"kožich","fur coat"},
  {"krajka","lace"},{"královna","queen"},{"království","kingdom"},{"krásně","beautifully"},
  {"kráva","cow"},{"krejčí","tailor"},{"kresba","drawing"},{"kříž","cross"},
  {"křižovatka","crossroads"},{"křtiny","baptism"},
  // === L ===
  {"láhev","bottle"},{"láska","love"},{"lehký","light"},{"lék","medicine"},
  {"lékař","doctor"},{"lékárna","pharmacy"},{"lépe","better"},{"les","forest"},
  {"letiště","airport"},{"letní","summer"},{"léto","summer"},{"let","flight"},
  {"levný","cheap"},{"levý","left"},{"ležet","to lie"},{"líbit se","to like"},
  {"lid","people"},{"lidský","human"},{"líný","lazy"},{"list","leaf"},
  {"litr","liter"},{"logika","logic"},{"loď","ship"},{"loni","last year"},
  {"lov","hunt"},{"lůžko","bed"},
  {"labrador","labrador"},{"laciný","cheap"},{"ladění","tuning"},{"laguna","lagoon"},
  {"lahůdka","delicacy"},{"lakomý","greedy"},{"lampa","lamp"},{"lano","rope"},
  {"laser","laser"},{"laskavý","kind"},{"laterální","lateral"},{"lavice","bench"},
  {"lavina","avalanche"},{"lebka","skull"},{"ledek","saltpeter"},{"leden","January"},
  {"lednice","fridge"},{"ledovec","glacier"},{"legální","legal"},{"legenda","legend"},
  {"legie","legion"},{"legislativa","legislation"},{"legitimní","legitimate"},
  {"lehce","easily"},{"lehkost","lightness"},{"leknín","water lily"},{"lekce","lesson"},
  {"lenoch","lazy person"},{"lep","glue"},{"lepenka","cardboard"},{"lepidlo","glue"},
  {"lepší","better"},{"letadlo","airplane"},{"leták","flyer"},{"letec","pilot"},
  {"letmý","fleeting"},{"letokruh","tree ring"},{"letopočet","calendar year"},
  {"lev","lion"},{"levhart","leopard"},{"léčba","treatment"},{"léčit","to treat"},
  {"léčivý","medicinal"},{"lhář","liar"},{"lhát","to lie"},{"lhůta","deadline"},
  {"líbat","to kiss"},{"liberální","liberal"},{"líc","face"},{"licence","license"},
  {"lidstvo","humanity"},{"liga","league"},{"líh","alcohol"},{"likér","liqueur"},
  {"lilie","lily"},{"limit","limit"},{"linie","line"},{"linka","line"},
  {"lípa","linden"},{"líska","hazel"},{"listina","document"},{"listopad","November"},
  {"literatura","literature"},{"litovat","to regret"},{"liška","fox"},
  {"lokální","local"},{"lokalita","location"},{"loket","elbow"},{"lopata","shovel"},
  {"lotos","lotus"},{"louka","meadow"},{"loupit","to rob"},{"loupež","robbery"},
  {"louže","puddle"},{"ložnice","bedroom"},{"luk","bow"},{"luna","moon"},
  {"lusk","pod"},{"lůno","womb"},{"luxus","luxury"},{"lyže","ski"},
  {"lyžování","skiing"},{"lžíce","spoon"},
  // === M ===
  {"málo","little"},{"malý","small"},{"máma","mom"},{"mapa","map"},
  {"máslo","butter"},{"maso","meat"},{"matka","mother"},{"mazat","to spread"},
  {"médium","media"},{"medvěd","bear"},{"mech","moss"},{"měkký","soft"},
  {"méně","less"},{"menší","smaller"},{"město","city"},{"metr","meter"},
  {"metoda","method"},{"mezera","gap"},{"milion","million"},{"milovat","to love"},
  {"milý","nice"},{"mimo","outside"},{"minerální","mineral"},{"ministr","minister"},
  {"minulost","past"},{"minulý","past"},{"minuta","minute"},{"mír","peace"},
  {"místo","place"},{"místnost","room"},{"mladý","young"},{"mléko","milk"},
  {"mlha","fog"},{"mluvit","to speak"},{"mně","me"},{"mnohý","many"},
  {"modrý","blue"},{"moc","power"},{"moderní","modern"},{"možná","maybe"},
  {"možnost","possibility"},{"možný","possible"},{"moře","sea"},{"most","bridge"},
  {"motor","engine"},{"mouka","flour"},{"moudrý","wise"},{"moucha","fly"},
  {"mozek","brain"},{"mrak","cloud"},{"mrtvý","dead"},{"mrzet","to be sorry"},
  {"mříž","grid"},{"muž","man"},{"muzeum","museum"},{"my","we"},
  {"mysl","mind"},{"myslet","to think"},{"myš","mouse"},{"myšlenka","idea"},
  {"mýt","to wash"},{"mzda","wage"},
  {"macecha","stepmother"},{"magnetický","magnetic"},{"magistrát","magistrate"},
  {"maják","lighthouse"},{"majetek","property"},{"majitel","owner"},{"majonéza","mayonnaise"},
  {"majorita","majority"},{"maketa","model"},{"malba","painting"},{"malíř","painter"},
  {"malina","raspberry"},{"maminka","mommy"},{"manažer","manager"},{"manžel","husband"},
  {"manželka","wife"},{"manželství","marriage"},{"maska","mask"},{"masáž","massage"},
  {"matematik","mathematician"},{"matematika","mathematics"},{"materiál","material"},
  {"matice","matrix"},{"maturita","graduation"},{"mazlíček","pet"},{"mechanik","mechanic"},
  {"mechanismus","mechanism"},{"medaile","medal"},{"medicína","medicine"},
  {"meditace","meditation"},{"melodie","melody"},{"meloun","melon"},{"membrána","membrane"},
  {"měna","currency"},{"měnit","to change"},{"mentor","mentor"},{"menu","menu"},
  {"měření","measurement"},{"měřit","to measure"},{"městský","urban"},
  {"metafora","metaphor"},{"meteor","meteor"},{"metro","subway"},{"mezinárodní","international"},
  {"migrace","migration"},{"miláček","darling"},{"milence","lover"},{"milimetr","millimeter"},
  {"milník","milestone"},{"minerál","mineral"},{"minimum","minimum"},{"ministerstvo","ministry"},
  {"minorita","minority"},{"miska","bowl"},{"mise","mission"},{"mistr","master"},
  {"míček","ball"},{"míra","measure"},{"mísit","to mix"},{"míša","teddy bear"},
  {"mít","to have"},{"mládež","youth"},{"mlýn","mill"},{"množství","quantity"},
  {"mobil","mobile phone"},{"mobilní","mobile"},{"model","model"},{"módní","fashionable"},
  {"modlitba","prayer"},{"molekula","molecule"},{"moment","moment"},{"monarchie","monarchy"},
  {"monitor","monitor"},{"montáž","assembly"},{"monument","monument"},{"morálka","morality"},
  {"mořský","maritime"},{"motiv","motive"},{"motivace","motivation"},{"motto","motto"},
  {"moučník","dessert"},{"moudrost","wisdom"},{"množit","to multiply"},
  {"mráz","frost"},{"mrkev","carrot"},{"mrož","walrus"},{"mučit","to torture"},
  {"mudrc","sage"},{"mumie","mummy"},{"munice","ammunition"},{"muset","must"},
  {"mutace","mutation"},{"muzikant","musician"},{"mydlo","soap"},{"mýtus","myth"},
  // === N ===
  {"na","on"},{"nabídka","offer"},{"nábytek","furniture"},{"nad","above"},
  {"nadšený","excited"},{"náhoda","coincidence"},{"nahoru","up"},{"nacházet","to find"},
  {"náklad","cost"},{"nakupovat","to shop"},{"náměstí","square"},{"naopak","on the contrary"},
  {"nápad","idea"},{"například","for example"},{"napsat","to write"},{"národ","nation"},
  {"narodit se","to be born"},{"náročný","demanding"},{"nářadí","tools"},
  {"následovat","to follow"},{"nastoupit","to board"},{"náš","our"},
  {"naučit se","to learn"},{"návrat","return"},{"návštěva","visit"},
  {"název","name"},{"ne","no"},{"nebe","sky"},{"nebezpečný","dangerous"},
  {"nebo","or"},{"něco","something"},{"neděle","Sunday"},{"někdo","someone"},
  {"někdy","sometimes"},{"nemocnice","hospital"},{"nemocný","sick"},
  {"nepřítel","enemy"},{"nervózní","nervous"},{"nést","to carry"},
  {"než","than"},{"nic","nothing"},{"nikdo","nobody"},{"nikdy","never"},
  {"nízký","low"},{"noc","night"},{"noha","leg"},{"normální","normal"},
  {"nos","nose"},{"nosit","to wear"},{"nový","new"},{"noviny","newspaper"},
  {"nůž","knife"},{"nutný","necessary"},
  {"naběračka","ladle"},{"nabíjet","to charge"},{"nabýt","to gain"},
  {"náčelník","chief"},{"nacismus","nazism"},{"náčrt","sketch"},{"nadace","foundation"},
  {"nadávat","to swear"},{"nadbytek","surplus"},{"nádherný","gorgeous"},
  {"nadměrný","excessive"},{"nadpis","heading"},{"nadpřirozený","supernatural"},
  {"nadsázka","exaggeration"},{"nafta","diesel"},{"náhle","suddenly"},
  {"náhradní","spare"},{"náhražka","substitute"},{"nahý","naked"},
  {"nájemník","tenant"},{"nakládat","to load"},{"nakonec","in the end"},
  {"nákup","purchase"},{"nákupní","shopping"},{"nálada","mood"},{"nálet","air raid"},
  {"nalézt","to find"},{"naložit","to load"},{"námaha","effort"},
  {"náměstek","deputy"},{"námořník","sailor"},{"nanometr","nanometer"},
  {"napadnout","to attack"},{"nápis","inscription"},{"nápoj","drink"},
  {"napětí","tension"},{"napodobit","to imitate"},{"náprava","axle"},
  {"naprostý","absolute"},{"naproti","opposite"},{"narovnat","to straighten"},
  {"narůst","to grow"},{"nasadit","to put on"},{"následek","consequence"},
  {"následně","subsequently"},{"násilí","violence"},{"násobilit","to multiply"},
  {"nástěnka","bulletin board"},{"nástroj","tool"},{"nástup","start"},
  {"naštěstí","fortunately"},{"nátěr","coating"},{"natočit","to film"},
  {"naučný","educational"},{"náušnice","earring"},{"návod","instructions"},
  {"návštěvník","visitor"},{"názor","opinion"},{"nebeský","heavenly"},
  {"nebezpečí","danger"},{"neblahý","unfortunate"},{"nechat","to let"},
  {"nedávno","recently"},{"nedbalý","negligent"},{"nedostatek","lack"},
  {"neformální","informal"},{"negativní","negative"},{"nehet","nail"},
  {"nehoda","accident"},{"nehorázný","outrageous"},{"nechuť","disgust"},
  {"nejen","not only"},{"nejistota","uncertainty"},{"nekonečný","infinite"},
  {"nelze","cannot"},{"němý","mute"},{"nenávist","hatred"},
  {"neobvyklý","unusual"},{"neočekávaný","unexpected"},{"neohrožený","fearless"},
  {"nepořádek","mess"},{"nepravda","untruth"},{"neprůstřelný","bulletproof"},
  {"nerost","mineral"},{"neřest","vice"},{"nesouhlas","disagreement"},
  {"nestabilní","unstable"},{"nestor","nestor"},{"neštěstí","misfortune"},
  {"netopýr","bat"},{"neutrální","neutral"},{"nevěsta","bride"},
  {"neviditelný","invisible"},{"nevinný","innocent"},{"nevlídný","unfriendly"},
  {"nezávislý","independent"},{"nit","thread"},{"nitro","interior"},
  {"noční","night"},{"nominace","nomination"},{"norma","norm"},
  {"normálně","normally"},{"nostalgie","nostalgia"},{"nota","note"},
  {"notebook","notebook"},{"nouze","need"},{"novela","amendment"},
  {"novinář","journalist"},{"novinka","novelty"},{"nuda","boredom"},
  {"nudle","noodle"},{"nutit","to force"},{"nůžky","scissors"},
  // === O ===
  {"oba","both"},{"obchod","shop"},{"obdivovat","to admire"},{"období","period"},
  {"obědvat","to have lunch"},{"obejít","to go around"},{"obětovat","to sacrifice"},
  {"obyvatel","inhabitant"},{"obraz","picture"},{"obsah","content"},
  {"obtížný","difficult"},{"obvyklý","usual"},{"obyčejný","ordinary"},
  {"oceán","ocean"},{"oči","eyes"},{"od","from"},{"odejít","to leave"},
  {"odpočinek","rest"},{"odpovědět","to answer"},{"odpověď","answer"},
  {"odpoledne","afternoon"},{"oheň","fire"},{"ohromný","enormous"},
  {"okamžik","moment"},{"okno","window"},{"oko","eye"},{"okolo","around"},
  {"olej","oil"},{"on","he"},{"ona","she"},{"ono","it"},
  {"opakovat","to repeat"},{"opravdu","really"},{"oranžový","orange"},
  {"organizace","organization"},{"oslava","celebration"},{"osm","eight"},
  {"osoba","person"},{"osobní","personal"},{"ostrý","sharp"},{"ostrov","island"},
  {"otázka","question"},{"otec","father"},{"otevřít","to open"},{"ovoce","fruit"},
  {"ovšem","however"},{"oznámit","to announce"},
  {"obálka","envelope"},{"oběd","lunch"},{"oběh","circulation"},{"oběť","victim"},
  {"objekt","object"},{"objem","volume"},{"objev","discovery"},{"objevit","to discover"},
  {"oblast","area"},{"oblečení","clothing"},{"oblékat","to dress"},{"oblíbený","favorite"},
  {"obloha","sky"},{"oblouk","arc"},{"obnova","renewal"},{"obočí","eyebrow"},
  {"obojek","collar"},{"obor","field"},{"obrana","defense"},{"obrátit","to turn"},
  {"obrna","polio"},{"obrys","outline"},{"obsadit","to occupy"},
  {"obsluha","service"},{"obstát","to pass"},{"obtěžovat","to bother"},
  {"obvaz","bandage"},{"obvod","circuit"},{"obyvatelstvo","population"},
  {"obžaloba","prosecution"},{"ocas","tail"},{"ocel","steel"},{"ocenit","to appreciate"},
  {"ocet","vinegar"},{"ochota","willingness"},{"ochrana","protection"},
  {"odborník","specialist"},{"odborný","professional"},{"odbory","unions"},
  {"oddělení","department"},{"oděv","garment"},{"odhadnout","to estimate"},
  {"odchod","departure"},{"odkaz","reference"},{"odlišný","different"},
  {"odmítnout","to refuse"},{"odměna","reward"},{"odnést","to take away"},
  {"odpad","waste"},{"odpor","resistance"},{"odpouštět","to forgive"},
  {"odpovědnost","responsibility"},{"odrazit","to reflect"},{"odsoudit","to condemn"},
  {"odstín","shade"},{"odstranit","to remove"},{"odtud","from here"},
  {"odvaha","courage"},{"odvětví","industry"},{"ohlas","response"},
  {"ohnisko","focus"},{"ohrada","fence"},{"ohrožení","threat"},
  {"okamžitý","immediate"},{"okouzlit","to enchant"},{"okres","district"},
  {"okruh","circuit"},{"okurka","cucumber"},{"olovo","lead"},{"olympiáda","olympics"},
  {"omáčka","sauce"},{"omeleta","omelette"},{"omezit","to limit"},
  {"omluva","apology"},{"onemocnět","to fall ill"},{"opera","opera"},
  {"operace","operation"},{"opice","monkey"},{"opora","support"},
  {"opozice","opposition"},{"oprávnění","authorization"},{"oprava","repair"},
  {"optimismus","optimism"},{"optický","optical"},{"orel","eagle"},
  {"organizovat","to organize"},{"orientace","orientation"},{"originál","original"},
  {"ornamenty","ornaments"},{"osada","settlement"},{"oslavit","to celebrate"},
  {"oslnivý","dazzling"},{"osnova","outline"},{"ospalý","sleepy"},
  {"ostatní","other"},{"osten","sting"},{"ostuda","disgrace"},
  {"osud","fate"},{"osvětlení","lighting"},{"ošetřit","to treat"},
  {"otáčet","to rotate"},{"otisk","fingerprint"},{"otrava","poisoning"},
  {"otrok","slave"},{"otvírat","to open"},{"ověřit","to verify"},
  {"ovládat","to control"},{"ovlivnit","to influence"},{"označit","to mark"},
  {"ozdoba","decoration"},{"ozon","ozone"},
  // === P ===
  {"padat","to fall"},{"pak","then"},{"palác","palace"},{"pamatovat","to remember"},
  {"pán","mister"},{"paní","mrs"},{"papír","paper"},{"park","park"},
  {"partner","partner"},{"pas","passport"},{"patro","floor"},{"pátek","Friday"},
  {"patřit","to belong"},{"pěkný","nice"},{"peníze","money"},{"pes","dog"},
  {"pět","five"},{"pevný","solid"},{"pivo","beer"},{"plán","plan"},
  {"platit","to pay"},{"plný","full"},{"plyn","gas"},{"po","after"},
  {"počasí","weather"},{"počet","number"},{"počítač","computer"},
  {"pod","under"},{"podívat se","to look"},{"podlaha","floor"},
  {"podmínka","condition"},{"podnos","tray"},{"podobný","similar"},
  {"podpora","support"},{"pohled","look"},{"pohyb","movement"},
  {"pokoj","room"},{"pokračovat","to continue"},{"pokud","if"},
  {"pole","field"},{"polévka","soup"},{"policie","police"},
  {"politika","politics"},{"poloha","position"},{"pomalu","slowly"},
  {"pomoc","help"},{"pondělí","Monday"},{"ponožky","socks"},
  {"pořád","still"},{"pořádek","order"},{"poslat","to send"},
  {"poslední","last"},{"postel","bed"},{"potíž","trouble"},
  {"potom","then"},{"potraviny","groceries"},{"potřeba","need"},
  {"potřebovat","to need"},{"použít","to use"},{"pouze","only"},
  {"považovat","to consider"},{"povídat","to talk"},{"pozice","position"},
  {"poznámka","note"},{"poznat","to recognize"},{"pozdě","late"},
  {"práce","work"},{"pracovat","to work"},{"praní","laundry"},
  {"prášek","powder"},{"pravda","truth"},{"pravý","right"},
  {"prázdný","empty"},{"první","first"},{"prý","allegedly"},
  {"přání","wish"},{"předmět","subject"},{"přes","over"},
  {"překvapení","surprise"},{"přesný","exact"},{"přesto","nevertheless"},
  {"při","at"},{"příběh","story"},{"příčina","cause"},
  {"přijít","to come"},{"příklad","example"},{"příliš","too much"},
  {"přímý","direct"},{"přinést","to bring"},{"příroda","nature"},
  {"přírodní","natural"},{"přítel","friend"},{"problém","problem"},
  {"proč","why"},{"prodej","sale"},{"profesor","professor"},
  {"program","program"},{"prohlídka","tour"},{"projekt","project"},
  {"prosím","please"},{"prostě","simply"},{"prostor","space"},
  {"prostředí","environment"},{"proti","against"},{"proto","therefore"},
  {"proud","stream"},{"provoz","operation"},{"průměrný","average"},
  {"průmysl","industry"},{"průvodce","guide"},{"pryč","away"},
  {"psát","to write"},{"pták","bird"},{"půl","half"},
  {"půlnoc","midnight"},{"pustit","to let go"},
  {"pacient","patient"},{"pachatel","perpetrator"},{"palec","thumb"},
  {"paleta","palette"},{"palivо","fuel"},{"palivo","fuel"},{"pamětník","witness"},
  {"paměť","memory"},{"panenka","doll"},{"panika","panic"},{"panorama","panorama"},
  {"panovat","to rule"},{"papež","pope"},{"paprika","pepper"},{"paradox","paradox"},
  {"paragraf","paragraph"},{"parlament","parliament"},{"parkoviště","parking lot"},
  {"partie","party"},{"paruka","wig"},{"pasažér","passenger"},{"pasta","paste"},
  {"patent","patent"},{"patriot","patriot"},{"patrona","cartridge"},
  {"pavouk","spider"},{"pazourek","flint"},{"pecka","pit"},{"pedagog","educator"},
  {"pekárna","bakery"},{"peklo","hell"},{"pelech","lair"},{"pendl","commuter"},
  {"penze","pension"},{"pepř","pepper"},{"perioda","period"},{"perla","pearl"},
  {"pero","pen"},{"perspektiva","perspective"},{"pestrost","diversity"},
  {"pestrý","colorful"},{"pěšky","on foot"},{"petice","petition"},
  {"petrolej","kerosene"},{"pevnina","mainland"},{"pevnost","fortress"},
  {"piano","piano"},{"píseň","song"},{"písek","sand"},{"pismeno","letter"},
  {"písnička","song"},{"pití","drinking"},{"plakat","to cry"},{"plakát","poster"},
  {"plameny","flames"},{"planeta","planet"},{"plást","honeycomb"},{"plášť","coat"},
  {"platba","payment"},{"platforma","platform"},{"platnost","validity"},
  {"plavat","to swim"},{"plavba","cruise"},{"plavec","swimmer"},{"plech","tin"},
  {"pleš","bald spot"},{"plevel","weed"},{"plíce","lungs"},{"plnit","to fulfill"},
  {"plocha","area"},{"plodina","crop"},{"plošina","platform"},{"plot","fence"},
  {"plovárna","swimming pool"},{"pluh","plow"},{"pluk","regiment"},
  {"plurál","plural"},{"plus","plus"},{"pneumatika","tire"},
  {"pobřeží","coast"},{"pocit","feeling"},{"počátek","beginning"},
  {"počítání","counting"},{"počítačový","computer"},{"podání","submission"},
  {"poddaný","subject"},{"podezření","suspicion"},{"podíl","share"},
  {"podnik","enterprise"},{"podnikatel","entrepreneur"},{"podnikání","business"},
  {"podpis","signature"},{"podrobnost","detail"},{"podstata","essence"},
  {"podvod","fraud"},{"podzemí","underground"},{"poezie","poetry"},
  {"pohanět","to disgrace"},{"pohanka","buckwheat"},{"pohár","cup"},
  {"pohoda","well-being"},{"pohodlí","comfort"},{"pohodlný","comfortable"},
  {"pohon","drive"},{"pohostinný","hospitable"},{"pohřeb","funeral"},
  {"pointa","punchline"},{"pokladna","cash register"},{"poklona","bow"},
  {"pokora","humility"},{"pokrm","dish"},{"pokrok","progress"},
  {"pokuta","fine"},{"poledne","noon"},{"polemika","controversy"},
  {"poleno","log"},{"poletovat","to flutter"},{"poloostrov","peninsula"},
  {"pomeranč","orange"},{"pomník","monument"},{"pomsta","revenge"},
  {"pondělek","Monday"},{"ponorka","submarine"},{"poplatek","fee"},
  {"populární","popular"},{"poradce","advisor"},{"porada","meeting"},
  {"porost","vegetation"},{"portrét","portrait"},{"porucha","malfunction"},
  {"posadit se","to sit down"},{"posádka","crew"},{"posílat","to send"},
  {"poslání","mission"},{"poslanec","deputy"},{"posledně","last time"},
  {"posluchač","listener"},{"posouvat","to move"},{"postava","figure"},
  {"postoj","attitude"},{"postup","procedure"},{"posvátný","sacred"},
  {"pošta","post office"},{"poškozený","damaged"},{"potenciál","potential"},
  {"potkat","to meet"},{"potopa","flood"},{"potůček","stream"},
  {"potvrzení","confirmation"},{"poušť","desert"},{"poutník","pilgrim"},
  {"pouto","bond"},{"povaha","character"},{"povinnost","duty"},
  {"povinný","mandatory"},{"povolání","occupation"},{"povolení","permission"},
  {"površka","surface"},{"povyk","uproar"},{"povznést","to elevate"},
  {"pozadí","background"},{"pozastavit","to pause"},{"pozdrav","greeting"},
  {"pozemek","plot"},{"pozitivní","positive"},{"pozornost","attention"},
  {"pozorovat","to observe"},{"pozvánka","invitation"},{"požár","fire"},
  {"požadavek","requirement"},{"požitek","pleasure"},
  {"pracovník","worker"},{"prach","dust"},{"praktický","practical"},
  {"prase","pig"},{"praxe","practice"},{"právě","just now"},
  {"právní","legal"},{"právník","lawyer"},{"pravidlo","rule"},
  {"praxe","experience"},{"předchůdce","predecessor"},{"předek","ancestor"},
  {"předevšíml","above all"},{"přednost","priority"},{"předpis","regulation"},
  {"předpověď","forecast"},{"předseda","chairman"},{"představa","idea"},
  {"představení","performance"},{"předsudek","prejudice"},{"předtím","before"},
  {"preference","preference"},{"premiér","prime minister"},{"prezident","president"},
  {"princezna","princess"},{"princip","principle"},{"priorita","priority"},
  {"privátní","private"},{"privilegium","privilege"},{"proces","process"},
  {"procento","percent"},{"prodavač","salesman"},{"produkce","production"},
  {"produkt","product"},{"profesionální","professional"},{"profil","profile"},
  {"prognóza","prognosis"},{"projev","speech"},{"prokázat","to prove"},
  {"propaganda","propaganda"},{"propojení","connection"},{"proporce","proportion"},
  {"pronásledovat","to persecute"},{"prořezat","to prune"},{"prospěch","benefit"},
  {"protest","protest"},{"protivník","opponent"},{"protiklad","contrast"},
  {"protokol","protocol"},{"provést","to carry out"},{"prozkoumat","to explore"},
  {"průběh","course"},{"průhledný","transparent"},{"průchod","passage"},
  {"průkaz","ID card"},{"průlom","breakthrough"},{"průsmyk","pass"},
  {"průzkum","survey"},{"prvek","element"},{"pstruh","trout"},
  {"psychiatr","psychiatrist"},{"publikace","publication"},{"puch","stench"},
  {"půda","soil"},
  // === R ===
  {"rád","glad"},{"rada","advice"},{"radost","joy"},{"ráno","morning"},
  {"reakce","reaction"},{"recept","recipe"},{"region","region"},
  {"reklama","advertisement"},{"republika","republic"},{"restaurace","restaurant"},
  {"riziko","risk"},{"rodina","family"},{"rok","year"},{"román","novel"},
  {"rostlina","plant"},{"rovný","straight"},{"rozbít","to break"},
  {"rozhodnutí","decision"},{"rozhovor","interview"},{"rozdíl","difference"},
  {"rozumět","to understand"},{"ručník","towel"},{"ruka","hand"},
  {"různý","various"},{"ryba","fish"},{"rychlý","fast"},{"rýže","rice"},
  {"radiátor","radiator"},{"radikální","radical"},{"rádio","radio"},
  {"radnice","town hall"},{"rajče","tomato"},{"raketa","rocket"},{"rakev","coffin"},
  {"rám","frame"},{"rameno","shoulder"},{"rána","wound"},{"raněný","wounded"},
  {"rarita","rarity"},{"rasa","race"},{"razítko","stamp"},{"reagovat","to react"},
  {"realita","reality"},{"realistický","realistic"},{"realizace","realization"},
  {"rebel","rebel"},{"recepcl","reception"},{"recese","recession"},{"recyklace","recycling"},
  {"redaktor","editor"},{"referát","report"},{"reforma","reform"},{"regál","shelf"},
  {"registrace","registration"},{"rehabilitace","rehabilitation"},{"rejstřík","register"},
  {"rekreace","recreation"},{"relikvie","relic"},{"renta","annuity"},
  {"repertoár","repertoire"},{"reportáž","report"},{"reprezentace","representation"},
  {"reprodukce","reproduction"},{"respekt","respect"},{"restaurovat","to restore"},
  {"revoluce","revolution"},{"rezerva","reserve"},{"režie","directing"},
  {"režim","regime"},{"režisér","director"},{"rodák","native"},
  {"rodič","parent"},{"rodinný","family"},{"rodiště","birthplace"},
  {"rohož","mat"},{"rok","year"},{"role","role"},{"romance","romance"},
  {"romantický","romantic"},{"ropa","oil"},{"rosa","dew"},{"rost","growth"},
  {"rotace","rotation"},{"roucho","robe"},{"rovnice","equation"},
  {"rovnováha","balance"},{"rozbitý","broken"},{"rozčilený","upset"},
  {"rozdělit","to divide"},{"rozeznávat","to distinguish"},{"rozhlédnout","to look around"},
  {"rozhled","overview"},{"rozhodni","decide"},{"rozchod","breakup"},
  {"rozkvět","bloom"},{"rozloha","area"},{"rozložit","to decompose"},
  {"rozmach","boom"},{"rozmanitý","diverse"},{"rozmluva","conversation"},
  {"rozpad","disintegration"},{"rozpočet","budget"},{"rozpor","contradiction"},
  {"rozptýlit","to scatter"},{"rozsah","range"},{"rozsudek","verdict"},
  {"roztomilý","cute"},{"rozvoj","development"},{"rtuť","mercury"},
  {"rubín","ruby"},{"ruch","bustle"},{"rudý","red"},{"rukavice","glove"},
  {"rukopis","manuscript"},{"ruský","Russian"},{"růst","growth"},
  {"růže","rose"},{"rybář","fisherman"},{"rybník","pond"},{"rychlost","speed"},
  {"rytíř","knight"},{"rytmus","rhythm"},{"rýsovat","to draw"},
  // === Ř ===
  {"řada","row"},{"řeka","river"},{"řešení","solution"},{"řešit","to solve"},
  {"říct","to say"},{"řídit","to drive"},{"řidič","driver"},
  {"řád","order"},{"řasa","algae"},{"řecký","Greek"},{"řeč","speech"},
  {"ředitel","director"},{"řemeslník","craftsman"},{"řemeslo","craft"},
  {"řepa","beet"},{"řetěz","chain"},{"řetízek","necklace"},{"řev","roar"},
  {"řezat","to cut"},{"řezník","butcher"},{"říjen","October"},
  {"římský","Roman"},{"říp","turnip"},{"říše","empire"},{"řízek","schnitzel"},
  {"řízení","management"},
  // === S ===
  {"sám","alone"},{"samozřejmě","of course"},{"schodiště","stairs"},
  {"schopný","capable"},{"schůzka","meeting"},{"sedět","to sit"},
  {"sedm","seven"},{"sednout si","to sit down"},{"sestra","sister"},
  {"sever","north"},{"seznam","list"},{"silný","strong"},{"síla","strength"},
  {"situace","situation"},{"skládat","to compose"},{"sklo","glass"},
  {"skoro","almost"},{"skrz","through"},{"skupina","group"},
  {"skutečný","real"},{"sladký","sweet"},{"slavný","famous"},
  {"slečna","miss"},{"slepý","blind"},{"slibovat","to promise"},
  {"slovo","word"},{"služba","service"},{"slyšet","to hear"},
  {"smát se","to laugh"},{"směr","direction"},{"smrt","death"},
  {"smutný","sad"},{"snad","perhaps"},{"snaha","effort"},
  {"snadný","easy"},{"snažit se","to try"},{"snídat","to have breakfast"},
  {"sníh","snow"},{"sny","dreams"},{"sobota","Saturday"},
  {"soused","neighbor"},{"současný","current"},{"soukromý","private"},
  {"souviset","to relate"},{"spát","to sleep"},{"speciální","special"},
  {"společnost","society"},{"spokojený","satisfied"},{"sport","sport"},
  {"správný","correct"},{"srpen","August"},{"srdce","heart"},
  {"stačit","to be enough"},{"stále","constantly"},{"stanice","station"},
  {"stará","old"},{"starý","old"},{"stát","state"},{"stát se","to happen"},
  {"stavba","building"},{"stěna","wall"},{"stesk","longing"},
  {"stisk","press"},{"sto","hundred"},{"strana","side"},
  {"strašný","scary"},{"strom","tree"},{"stroj","machine"},
  {"středa","Wednesday"},{"studený","cold"},{"studovat","to study"},
  {"stůl","table"},{"stupeň","degree"},{"suchý","dry"},
  {"sukně","skirt"},{"svět","world"},{"světlo","light"},
  {"svoboda","freedom"},{"svobodný","free"},{"svůj","own"},
  {"syn","son"},{"systém","system"},
  {"sádra","plaster"},{"salám","salami"},{"salát","salad"},{"samota","solitude"},
  {"samovolný","spontaneous"},{"sandál","sandal"},{"saně","sled"},{"satelit","satellite"},
  {"sazba","rate"},{"sbírka","collection"},{"sbor","choir"},{"scéna","scene"},
  {"schéma","scheme"},{"schizofrenie","schizophrenia"},{"schody","stairs"},
  {"schopnost","ability"},{"schovat","to hide"},{"schůze","meeting"},
  {"sedadlo","seat"},{"sedlák","farmer"},{"segment","segment"},
  {"sekce","section"},{"sekera","axe"},{"sekretář","secretary"},
  {"selhání","failure"},{"semínko","seed"},{"seno","hay"},{"senior","senior"},
  {"senzace","sensation"},{"série","series"},{"seriózní","serious"},
  {"server","server"},{"setkat se","to meet"},{"setkání","meeting"},
  {"sever","north"},{"sevřít","to clench"},{"sezóna","season"},
  {"shoda","agreement"},{"shromáždění","assembly"},{"signál","signal"},
  {"silnice","road"},{"singl","single"},{"sirotek","orphan"},
  {"skákat","to jump"},{"skála","rock"},{"skandál","scandal"},
  {"skaut","scout"},{"skeptický","skeptical"},{"skica","sketch"},
  {"sklárna","glassworks"},{"sklad","warehouse"},{"skladatel","composer"},
  {"sklenice","glass"},{"sklep","cellar"},{"sklon","tendency"},
  {"skóre","score"},{"skořice","cinnamon"},{"skot","cattle"},
  {"skromný","modest"},{"skříň","wardrobe"},{"skulptura","sculpture"},
  {"skutek","deed"},{"slabina","weakness"},{"slabý","weak"},
  {"sláma","straw"},{"slanina","bacon"},{"slaný","salty"},
  {"sláva","glory"},{"slavnost","ceremony"},{"slečinka","young lady"},
  {"sledovat","to follow"},{"slepice","hen"},{"sleva","discount"},
  {"slévárna","foundry"},{"slib","promise"},{"slina","saliva"},
  {"slitek","ingot"},{"slitina","alloy"},{"sloh","style"},
  {"složení","composition"},{"složitý","complex"},{"složka","folder"},
  {"sluch","hearing"},{"slunce","sun"},{"sluneční","solar"},
  {"slušný","decent"},{"služebník","servant"},{"smaragd","emerald"},
  {"směna","shift"},{"směnárna","exchange office"},{"směnka","bill of exchange"},
  {"směs","mixture"},{"směšný","ridiculous"},{"smích","laughter"},
  {"smír","reconciliation"},{"smlouva","contract"},{"smog","smog"},
  {"smysl","sense"},{"smyslný","sensual"},{"snacha","daughter-in-law"},
  {"snášet","to tolerate"},{"sněhulák","snowman"},{"sněžit","to snow"},
  {"snídat","to have breakfast"},{"snídaně","breakfast"},{"snímek","picture"},
  {"socha","statue"},{"sociální","social"},{"sochař","sculptor"},
  {"sodovka","soda"},{"sojka","jay"},{"sokol","falcon"},
  {"solidární","solidarity"},{"solit","to salt"},{"sólový","solo"},
  {"sonda","probe"},{"sopka","volcano"},{"sotva","barely"},
  {"soucit","compassion"},{"soud","court"},{"soudce","judge"},
  {"souhlas","agreement"},{"souhrn","summary"},{"soupeř","rival"},
  {"souprava","set"},{"souřadnice","coordinates"},{"soustava","system"},
  {"soutěž","competition"},{"souvětí","compound sentence"},{"souvislost","context"},
  {"spadnout","to fall"},{"spalovat","to burn"},{"spánek","sleep"},
  {"spára","crack"},{"specifický","specific"},{"spektrum","spectrum"},
  {"spěch","hurry"},{"spirála","spiral"},{"spisovat","to write"},
  {"splnit","to fulfill"},{"spojenec","ally"},{"spojení","connection"},
  {"spolehlivý","reliable"},{"společný","common"},{"spolupráce","cooperation"},
  {"spontánní","spontaneous"},{"sporný","controversial"},{"spořit","to save"},
  {"spotřeba","consumption"},{"spravedlivý","fair"},{"správa","administration"},
  {"spropitné","tip"},{"sprcha","shower"},{"spustit","to launch"},
  {"sráz","cliff"},{"stabilní","stable"},{"stadion","stadium"},
  {"stádo","herd"},{"stáhnou","to download"},{"stánek","stall"},
  {"starost","worry"},{"starosta","mayor"},{"starověk","antiquity"},
  {"statistika","statistics"},{"stavět","to build"},{"stávka","strike"},
  {"stejný","same"},{"stezka","path"},{"stín","shadow"},
  {"stížnost","complaint"},{"stodola","barn"},{"stolek","small table"},
  {"století","century"},{"stopa","trace"},{"stopař","hitchhiker"},
  {"stoupat","to rise"},{"strach","fear"},{"strategie","strategy"},
  {"strava","food"},{"stráž","guard"},{"strážník","officer"},
  {"střela","bullet"},{"střelec","shooter"},{"střet","clash"},
  {"střecha","roof"},{"střih","cut"},{"střízlivý","sober"},
  {"struktura","structure"},{"struna","string"},{"student","student"},
  {"studie","study"},{"studna","well"},{"stvořit","to create"},
  {"styl","style"},{"sucho","drought"},{"sud","barrel"},
  {"sultán","sultan"},{"suma","sum"},{"supermarket","supermarket"},
  {"surový","raw"},{"svah","slope"},{"sval","muscle"},
  {"svatba","wedding"},{"svatý","holy"},{"svaz","union"},
  {"svědek","witness"},{"svědomí","conscience"},{"svěřit","to entrust"},
  {"svěží","fresh"},{"světový","worldwide"},{"svíčka","candle"},
  {"svítit","to shine"},{"symbol","symbol"},{"symfonie","symphony"},
  {"sympatický","sympathetic"},{"synagoga","synagogue"},{"synchronizace","synchronization"},
  // === Š ===
  {"šance","chance"},{"šaty","dress"},{"šedý","grey"},{"šéf","boss"},
  {"šest","six"},{"šířka","width"},{"škoda","damage"},{"škola","school"},
  {"špatný","bad"},{"šťastný","happy"},{"šunka","ham"},
  {"šálek","cup"},{"šaman","shaman"},{"šampión","champion"},{"šarlatán","charlatan"},
  {"šátek","scarf"},{"šatna","cloakroom"},{"šedivý","grey"},{"šelma","beast"},
  {"šerpa","sherpa"},{"šetřit","to save"},{"šikovný","handy"},{"šílenec","madman"},
  {"šílenost","madness"},{"šílený","crazy"},{"šíp","arrow"},{"široký","wide"},
  {"šít","to sew"},{"škaredý","ugly"},{"škeble","clam"},{"školák","schoolboy"},
  {"školení","training"},{"školka","kindergarten"},{"škrábat","to scratch"},
  {"škrtnout","to cross out"},{"škvíra","crack"},{"šlechta","nobility"},
  {"šlépěj","footprint"},{"šňůra","cord"},{"šofér","chauffeur"},
  {"šokovat","to shock"},{"špagáty","splits"},{"španělský","Spanish"},
  {"špatně","badly"},{"šperk","jewel"},{"špička","tip"},
  {"šplhat","to climb"},{"šroub","screw"},{"šťáva","juice"},
  {"štědrý","generous"},{"štěně","puppy"},{"štěpka","chip"},
  {"štěstí","luck"},{"štít","shield"},{"štítek","label"},
  {"šváb","cockroach"},{"švagr","brother-in-law"},{"švec","shoemaker"},  // === T ===
  {"tady","here"},{"tah","move"},{"tajný","secret"},{"tak","so"},
  {"také","also"},{"takový","such"},{"talíř","plate"},{"tam","there"},
  {"táta","dad"},{"televize","television"},{"tělo","body"},
  {"temný","dark"},{"ten","that"},{"tento","this"},
  {"teplota","temperature"},{"teplý","warm"},{"teprve","only then"},
  {"terasa","terrace"},{"text","text"},{"těžký","heavy"},
  {"ticho","silence"},{"tichý","quiet"},{"tisíc","thousand"},
  {"tisk","print"},{"tlačítko","button"},{"tma","darkness"},
  {"tlak","pressure"},{"to","that"},{"toaleta","toilet"},
  {"tolik","so much"},{"továrna","factory"},{"tradice","tradition"},
  {"trávit","to spend"},{"trh","market"},{"trochu","a little"},
  {"troska","ruin"},{"trpělivý","patient"},{"trvat","to last"},
  {"tři","three"},{"třída","class"},{"tu","here"},
  {"tudy","this way"},{"tuhý","stiff"},{"turista","tourist"},
  {"tvář","face"},{"tvor","creature"},{"tvrdý","hard"},
  {"tvůj","your"},{"ty","you"},{"týden","week"},{"typ","type"},
  {"typický","typical"},
  {"tahák","cheat sheet"},{"tajenka","hidden word"},{"tajemník","secretary"},
  {"tajemství","secret"},{"taktický","tactical"},{"taktika","tactics"},
  {"talent","talent"},{"talentovaný","talented"},{"tamten","that one"},
  {"tanec","dance"},{"taneční","dance"},{"tanečník","dancer"},
  {"tancovat","to dance"},{"tank","tank"},{"tapeta","wallpaper"},
  {"tatínek","daddy"},{"taxík","taxi"},{"technický","technical"},
  {"technika","technology"},{"technologie","technology"},{"téma","topic"},
  {"temnota","darkness"},{"tendencel","tendency"},{"tenis","tennis"},
  {"tenký","thin"},{"teoretický","theoretical"},{"teorie","theory"},
  {"teplo","warmth"},{"terén","terrain"},{"teror","terror"},
  {"teritorium","territory"},{"termín","term"},{"termostat","thermostat"},
  {"test","test"},{"testament","testament"},{"tetování","tattoo"},
  {"textil","textile"},{"těhotná","pregnant"},{"tělocvična","gym"},
  {"těsný","tight"},{"těsto","dough"},{"těšit se","to look forward"},
  {"tíseň","distress"},{"tíže","gravity"},
  {"tkáň","tissue"},{"tkanina","fabric"},{"tlumočník","interpreter"},
  {"tlusty","fat"},{"tmavý","dark"},{"tolerance","tolerance"},
  {"topení","heating"},{"topinka","toast"},{"torta","cake"},
  {"touha","longing"},{"toužit","to desire"},{"tragédie","tragedy"},
  {"trajekt","ferry"},{"trakt","tract"},{"traktor","tractor"},
  {"transparent","banner"},{"trasa","route"},{"tráva","grass"},
  {"trávník","lawn"},{"trest","punishment"},{"tribunál","tribunal"},
  {"tribuna","stand"},{"tričko","t-shirt"},{"triumf","triumph"},
  {"trolejbus","trolleybus"},{"trošku","a bit"},{"trouba","oven"},
  {"trpět","to suffer"},{"trubka","trumpet"},{"truhlář","carpenter"},
  {"truhla","chest"},{"trup","torso"},{"trvalý","permanent"},
  {"třásat","to shake"},{"třešně","cherry"},{"třetí","third"},
  {"třetina","third"},{"třpytivý","sparkling"},{"tržiště","marketplace"},
  {"tržnice","market hall"},{"tuček","penguin"},{"tunel","tunnel"},
  {"turban","turban"},{"turbína","turbine"},{"turistický","tourist"},
  {"turistika","tourism"},{"tužka","pencil"},{"tvar","shape"},
  {"tvaroh","curd"},{"tvořit","to create"},{"tvorba","creation"},
  {"tvrzení","claim"},{"tygr","tiger"},{"tyran","tyrant"},
  // === U ===
  {"účet","bill"},{"udělat","to make"},{"ucho","ear"},
  {"ukazovat","to show"},{"uklidit","to clean"},{"ulice","street"},
  {"umění","art"},{"umět","to know how"},{"umýt","to wash"},
  {"unavený","tired"},{"univerzita","university"},{"upozornit","to warn"},
  {"uprostřed","in the middle"},{"určitě","certainly"},{"určitý","certain"},
  {"úřad","office"},{"uskutečnit","to realize"},{"úsměv","smile"},
  {"úspěch","success"},{"ústav","institute"},{"úterý","Tuesday"},
  {"útok","attack"},{"uvařit","to cook"},{"uvnitř","inside"},
  {"už","already"},{"úžasný","amazing"},{"užitečný","useful"},
  {"užívat si","to enjoy"},
  {"účast","participation"},{"účastník","participant"},{"účel","purpose"},
  {"účes","hairstyle"},{"účetní","accountant"},{"účinek","effect"},
  {"účinný","effective"},{"učebnice","textbook"},{"učení","learning"},
  {"učenec","scholar"},{"učit","to teach"},{"učitel","teacher"},
  {"učitelka","female teacher"},{"údaj","data"},{"událost","event"},
  {"udržet","to maintain"},{"udržovat","to maintain"},{"uhasit","to extinguish"},
  {"uhlí","coal"},{"uhradit","to pay"},{"ujasnit","to clarify"},
  {"ujistit","to assure"},{"ukazatel","indicator"},{"ukázka","demonstration"},
  {"uklidnit","to calm down"},{"ukončit","to end"},{"ukrást","to steal"},
  {"ukrýt","to hide"},{"úleva","relief"},{"ultimátum","ultimatum"},
  {"umělec","artist"},{"umělý","artificial"},{"uměřený","moderate"},
  {"umístění","placement"},{"umístit","to place"},{"umožnit","to enable"},
  {"umřít","to die"},{"unahlený","hasty"},{"uniforma","uniform"},
  {"unikátní","unique"},{"uniknout","to escape"},{"univerzální","universal"},
  {"únor","February"},{"únosný","bearable"},{"úpadek","decline"},
  {"upadnout","to fall"},{"upevnit","to fasten"},{"úplný","complete"},
  {"upoutat","to attract"},{"uprchlík","refugee"},{"upřímný","sincere"},
  {"úraz","injury"},{"určení","determination"},{"určovat","to determine"},
  {"úroda","harvest"},{"úroveň","level"},{"úřadovat","to officiate"},
  {"úředník","clerk"},{"úschovna","storage"},{"úsek","section"},
  {"usednout","to sit down"},{"usínat","to fall asleep"},{"úsilí","effort"},
  {"uskutečnění","realization"},{"usnadnit","to facilitate"},
  {"uspět","to succeed"},{"uspořádat","to organize"},{"ústava","constitution"},
  {"ústřice","oyster"},{"útěcha","consolation"},{"útěk","escape"},
  {"úterní","Tuesday"},{"utrpení","suffering"},{"utvořit","to form"},
  {"uvalit","to impose"},{"uvážit","to consider"},{"uvedení","introduction"},
  {"uvědomit","to realize"},{"uvolnit","to release"},{"uzamknout","to lock"},
  {"uzel","knot"},{"území","territory"},{"uznání","recognition"},
  {"užaslý","astonished"},{"uživatel","user"},{"užovka","grass snake"},
  // === V ===
  {"válka","war"},{"vana","bathtub"},{"varovat","to warn"},
  {"váš","your"},{"včera","yesterday"},{"vdova","widow"},
  {"ve","in"},{"večer","evening"},{"večeře","dinner"},
  {"vědět","to know"},{"vedlejší","side"},{"vedoucí","leader"},
  {"velice","very"},{"veliký","big"},{"velký","big"},
  {"venku","outside"},{"veřejný","public"},{"veselý","cheerful"},
  {"vesnice","village"},{"většina","majority"},{"většinou","mostly"},
  {"věc","thing"},{"věda","science"},{"vidět","to see"},
  {"viditelný","visible"},{"víkend","weekend"},{"víno","wine"},
  {"víra","faith"},{"vítat","to welcome"},{"vítr","wind"},
  {"vlastně","actually"},{"vlastní","own"},{"vlak","train"},
  {"vlevo","left"},{"vliv","influence"},{"voda","water"},
  {"voják","soldier"},{"volat","to call"},{"volba","choice"},
  {"volný","free"},{"volit","to choose"},{"vpravo","right"},
  {"vracet","to return"},{"vrátit","to return"},{"vrch","top"},
  {"vstát","to get up"},{"vstoupit","to enter"},{"vše","everything"},
  {"všechen","all"},{"vtip","joke"},{"vůbec","at all"},
  {"vůle","will"},{"vybrat","to choose"},{"východ","east"},
  {"výhodný","advantageous"},{"výjimka","exception"},{"výlet","trip"},
  {"vynález","invention"},{"vypadat","to look"},{"výraz","expression"},
  {"výsledek","result"},{"výstava","exhibition"},{"vysoký","high"},
  {"výtah","elevator"},{"význam","meaning"},{"vzduch","air"},
  {"vzít","to take"},{"vzniknout","to arise"},{"vzpomínat","to remember"},
  {"vášeň","passion"},{"vážit","to weigh"},{"vážný","serious"},
  {"vcelku","on the whole"},{"včelař","beekeeper"},{"včelín","beehive"},
  {"včetně","including"},{"vdávat se","to marry"},{"vděčný","grateful"},
  {"věčný","eternal"},{"vědomí","consciousness"},{"vědomost","knowledge"},
  {"vedro","heat"},{"vegetace","vegetation"},{"vejce","egg"},
  {"velbloud","camel"},{"veletrh","fair"},{"velitel","commander"},
  {"velikost","size"},{"velkoměsto","big city"},{"venkov","countryside"},
  {"ventil","valve"},{"ventilace","ventilation"},{"veřejnost","public"},
  {"verze","version"},{"veselost","cheerfulness"},{"veslo","oar"},
  {"vesmír","universe"},{"veterán","veteran"},{"veterinář","veterinarian"},
  {"větev","branch"},{"větrat","to ventilate"},{"větší","bigger"},
  {"většinový","majority"},{"věž","tower"},{"vězeň","prisoner"},
  {"vězení","prison"},{"vchod","entrance"},{"vícero","several"},
  {"vidlička","fork"},{"vidle","pitchfork"},{"vila","villa"},
  {"vinař","winemaker"},{"vinice","vineyard"},{"vinný","guilty"},
  {"viola","viola"},{"virtuální","virtual"},{"vítěz","winner"},
  {"vítězství","victory"},{"vizitka","business card"},{"vklady","deposits"},
  {"vláda","government"},{"vládce","ruler"},{"vládnout","to rule"},
  {"vlákno","fiber"},{"vlast","homeland"},{"vlastenec","patriot"},
  {"vlastnictví","ownership"},{"vlastník","owner"},{"vlastnost","property"},
  {"vlček","small wolf"},{"vlhký","humid"},{"vlhkost","humidity"},
  {"vlna","wave"},{"vlnění","undulation"},{"vložit","to insert"},
  {"vnější","external"},{"vnitřní","internal"},{"vnuk","grandson"},
  {"vnučka","granddaughter"},{"vodík","hydrogen"},{"vodítko","leash"},
  {"vodní","water"},{"vodopád","waterfall"},{"vodovod","water supply"},
  {"vojenský","military"},{"volant","steering wheel"},{"volně","freely"},
  {"vonět","to smell nice"},{"vosa","wasp"},{"vozidlo","vehicle"},
  {"vozík","cart"},{"vrabec","sparrow"},{"vrána","crow"},
  {"vráska","wrinkle"},{"vrstva","layer"},{"vrtulník","helicopter"},
  {"vsadit","to bet"},{"vstřícný","accommodating"},{"vstup","entrance"},
  {"vstupné","admission fee"},{"vsuvka","insertion"},{"vůdce","leader"},
  {"vulkán","volcano"},{"vůně","scent"},{"vybavení","equipment"},
  {"vybavit","to equip"},{"výběr","selection"},{"vyčerpat","to exhaust"},
  {"vydání","edition"},{"vydat","to publish"},{"vydělat","to earn"},
  {"výdej","dispensing"},{"vyděsit","to scare"},{"výhled","outlook"},
  {"vyhlásit","to declare"},{"výhra","win"},{"vyhrát","to win"},
  {"výhružka","threat"},{"vycházka","walk"},{"vychovat","to raise"},
  {"vyjednávání","negotiation"},{"výjezd","exit"},{"výkaz","report"},
  {"výkon","performance"},{"vykonat","to perform"},{"výkop","excavation"},
  {"vykoupat","to bathe"},{"výloha","shop window"},{"vyměnit","to exchange"},
  {"výměra","acreage"},{"vynahradit","to compensate"},{"výnos","yield"},
  {"výpis","statement"},{"výplata","salary"},{"vypnout","to turn off"},
  {"výpočet","calculation"},{"výprava","expedition"},{"vypravěč","narrator"},
  {"výroba","production"},{"výrobce","manufacturer"},{"výrobek","product"},
  {"výročí","anniversary"},{"výrok","statement"},{"vysílat","to broadcast"},
  {"výskyt","occurrence"},{"vyslechnout","to listen"},{"výslech","interrogation"},
  {"vyslovit","to pronounce"},{"výslovnost","pronunciation"},
  {"vyspělý","advanced"},{"výstava","exhibition"},{"výstražný","warning"},
  {"výstřel","shot"},{"výstup","output"},{"vysvětlit","to explain"},
  {"výše","above"},{"vyšetření","examination"},{"výtečný","excellent"},
  {"výtisk","copy"},{"využít","to use"},{"využití","utilization"},
  {"vývoj","development"},{"vývojář","developer"},{"vývoz","export"},
  {"vyznání","confession"},{"významný","significant"},{"výzva","challenge"},
  {"vzácný","rare"},{"vzdálenost","distance"},{"vzdělání","education"},
  {"vzdělávání","education"},{"vzestup","rise"},{"vzhled","appearance"},
  {"vzkazat","to send word"},{"vzkaz","message"},{"vznik","origin"},
  {"vzor","pattern"},{"vzorek","sample"},{"vzpoura","rebellion"},
  {"vzrůst","to increase"},{"vztah","relationship"},{"vztek","anger"},
  // === Z ===
  {"za","behind"},{"záchod","toilet"},{"začátek","beginning"},
  {"začít","to start"},{"záhada","mystery"},{"zájem","interest"},
  {"zajímavý","interesting"},{"zákazník","customer"},{"zákon","law"},
  {"základ","base"},{"základní","basic"},{"záležet","to depend"},
  {"západ","west"},{"zapomenout","to forget"},{"zápas","match"},
  {"zaplatit","to pay"},{"zároveň","at the same time"},
  {"zastávka","stop"},{"zavřít","to close"},{"zdraví","health"},
  {"zdravý","healthy"},{"zbraň","weapon"},{"zde","here"},
  {"zelenina","vegetables"},{"země","country"},{"zima","winter"},
  {"získat","to gain"},{"zítra","tomorrow"},{"život","life"},
  {"žlutý","yellow"},{"zlatý","golden"},{"zlo","evil"},
  {"změna","change"},{"změnit","to change"},{"značka","brand"},
  {"známý","known"},{"znovu","again"},{"zoologický","zoological"},
  {"zpátky","back"},{"zpěv","singing"},{"zpráva","news"},
  {"způsob","way"},{"zralý","ripe"},{"zrcadlo","mirror"},
  {"ztratit","to lose"},{"zub","tooth"},{"zůstat","to stay"},
  {"zvíře","animal"},{"zvláštní","special"},{"zvuk","sound"},
  {"zvyk","habit"},{"zvyšovat","to increase"},
  {"zabalit","to pack"},{"zábava","fun"},{"zábavný","entertaining"},
  {"zabezpečení","security"},{"zabít","to kill"},{"zábradlí","railing"},
  {"zabrat","to take up"},{"zabývat se","to deal with"},{"záclona","curtain"},
  {"začátečník","beginner"},{"začínat","to begin"},{"záda","back"},
  {"zadání","assignment"},{"zadarmo","for free"},{"zadek","bottom"},
  {"zahájet","to start"},{"zahrada","garden"},{"zahradník","gardener"},
  {"zahraniční","foreign"},{"záchrana","rescue"},{"záchranář","rescuer"},
  {"zajatec","prisoner"},{"zajíc","hare"},{"zajistit","to ensure"},
  {"zákaz","ban"},{"zákeřný","insidious"},{"základ","foundation"},
  {"základna","base"},{"zakladatel","founder"},{"zákazka","order"},
  {"zákon","law"},{"záležitost","matter"},{"záloha","deposit"},
  {"zamčený","locked"},{"zaměřit","to focus"},{"zaměstnanec","employee"},
  {"zaměstnání","employment"},{"zamknout","to lock"},{"zámek","castle"},
  {"zamítnout","to reject"},{"zanechat","to leave"},{"zánik","demise"},
  {"zanícený","passionate"},{"západ","west"},{"zapadnout","to fit in"},
  {"zápalka","match"},{"záplata","patch"},{"zapojit","to connect"},
  {"zapsat","to write down"},{"záření","radiation"},{"září","September"},
  {"zásada","principle"},{"zásah","intervention"},{"zásilka","shipment"},
  {"zásluha","merit"},{"zásnuby","engagement"},{"zásoba","supply"},
  {"zástěra","apron"},{"zástupce","representative"},{"zásuvka","socket"},
  {"zatáčka","curve"},{"zatěžovat","to burden"},{"zatím","so far"},
  {"zatímco","while"},{"zatknout","to arrest"},{"závazek","commitment"},
  {"závažný","serious"},{"závěr","conclusion"},{"závist","envy"},
  {"závisět","to depend"},{"závod","race"},{"závora","barrier"},
  {"závorka","bracket"},{"záznam","record"},{"zázrak","miracle"},
  {"zbabělý","cowardly"},{"zboží","goods"},{"zbytek","rest"},
  {"zbytečný","unnecessary"},{"zdánlivý","apparent"},{"zdařilý","successful"},
  {"zdejší","local"},{"zděšení","horror"},{"zdokonalit","to improve"},
  {"zdolat","to overcome"},{"zdráhat se","to hesitate"},{"zdravotní","health"},
  {"zdržet","to delay"},{"zdvořilý","polite"},{"zeď","wall"},
  {"zeleň","greenery"},{"zelený","green"},{"zemědělství","agriculture"},
  {"zeměkoule","globe"},{"zeměpis","geography"},{"zemřít","to die"},
  {"zeptat se","to ask"},{"zesilovat","to amplify"},{"zhodnotit","to evaluate"},
  {"zhruba","roughly"},{"zchudnout","to become poor"},{"zjistit","to find out"},
  {"zkáza","destruction"},{"zkoumavý","inquisitive"},{"zkoušet","to try"},
  {"zkouška","exam"},{"zkrátka","simply"},{"zkušenost","experience"},
  {"zkusit","to try"},{"zlepšit","to improve"},{"zlodějl","thief"},
  {"zlomit","to break"},{"zlost","anger"},{"zmapovat","to map"},
  {"zmátořit","to confuse"},{"zmínit","to mention"},{"zmizet","to disappear"},
  {"zmrzlina","ice cream"},{"značit","to mark"},{"značný","considerable"},
  {"znalost","knowledge"},{"znak","sign"},{"znalec","expert"},
  {"znamení","sign"},{"znamenat","to mean"},{"znát","to know"},
  {"znečištění","pollution"},{"zničit","to destroy"},{"znít","to sound"},
  {"zobrazit","to display"},{"zodpovědný","responsible"},{"zóna","zone"},
  {"zoufale","desperately"},{"zoufalý","desperate"},{"zpěvák","singer"},
  {"zpívat","to sing"},{"zpochybnit","to question"},{"zpovědník","confessor"},
  {"zpracovat","to process"},{"zprostředkovat","to mediate"},
  {"zpřístupnit","to make accessible"},{"zranění","injury"},{"zranit","to injure"},
  {"zrádce","traitor"},{"zrno","grain"},{"zrod","birth"},
  {"zrušit","to cancel"},{"ztišit","to quiet"},{"ztráta","loss"},
  {"ztvárnit","to portray"},{"zubař","dentist"},{"zuřivý","furious"},
  {"zúčastnit se","to participate"},{"zvědavý","curious"},{"zvěř","game"},
  {"zvětšit","to enlarge"},{"zvládnout","to manage"},{"zvolit","to elect"},
  {"zvonek","bell"},{"zvonit","to ring"},{"zvrat","twist"},
  {"zvýšit","to increase"},{"zvykat","to get used to"},
  // === Ž ===
  {"žádat","to request"},{"žák","student"},{"žádný","none"},
  {"že","that"},{"želva","turtle"},{"žena","woman"},
  {"živý","alive"},{"žízeň","thirst"},{"život","life"},
    {"životní","of life"},{"židle","chair"},
  {"žába","frog"},{"žaloba","lawsuit"},{"žalovat","to sue"},
  {"žalm","psalm"},{"žaludek","stomach"},{"žár","heat"},
  {"žárovka","light bulb"},{"žebřík","ladder"},{"žehlička","iron"},
  {"železnice","railway"},{"železný","iron"},{"železo","iron"},
  {"žemlička","roll"},{"ženich","groom"},{"ženský","female"},
  {"žert","joke"},{"žhavý","glowing"},{"žijící","living"},
  {"žiletka","razor blade"},{"živit","to feed"},{"živnost","trade"},
  {"živočich","animal"},{"životopis","biography"},{"žíla","vein"},
  {"žnec","reaper"},{"žně","harvest"},{"žokej","jockey"},
  {"žralok","shark"},{"žula","granite"},{"župan","bathrobe"},
  {"žurnalista","journalist"},{"žvýkačka","chewing gum"},
  };

const int slovnikDataCount = sizeof(slovnikData) / sizeof(slovnikData[0]);

#endif